### ISSUE TITLE
custom_dict should accept tibbles

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#121]

**Comment by vincentarelbundock** [comment]
currently only data.frames are accepted.

**Comment by cjyetman** [comment]
super simple way is to add something like this just before checking if it's a data.frame...
```r
if ('tbl_df' %in% class(dictionary)) dictionary <- as.data.frame(dictionary)
```

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countrycode/commit/3188ea709bb95970a2e079716edc51a78f447d23
