### ISSUE TITLE
Trinidad y Tobago has a typo

### ISSUE THREAD

**Issue by ricardomayerb** [vincentarelbundock/countrycode#122]
Version:  0.19, installed from github today

Problem: inside countrycode_data$country.name.es  the name Trinidad y Tobago is misspelled as Trinidad yTobago (there is a space missing after y)

Comment 1: Some agencies like UN's ECLAC spell it as Trinidad y Tabago ... notice the a instead of o in Tabago, just in case you want to look it up further.

Comment 2: Your package is awesome, by the way.

**Comment by vincentarelbundock** [comment]
Thanks for the notice!

We've been planning a new dictionary building process, which is being developed in a different repo for now. So this is fixed here: https://github.com/vincentarelbundock/countryyear/commit/7745de6810dcf3c5bc0445473a8eed366a2db581

Unfortunately, it's probably going to take a while before this is ported here, as free time is on short supply these days..
