### ISSUE TITLE
Centralize custom dictionaries on github

### ISSUE THREAD

**Issue by LaDilettante** [vincentarelbundock/countrycode#123]
Would you consider allowing users to contribute their custom dictionaries here or at some other repositories? For example, I'm having to convert / standardize city names and would love to contribute here.

In the docs, we can point users to this repository to find more common custom dicts (US states, country provinces, etc.)

**Comment by vincentarelbundock** [comment]
Yeah, I would love to add other data sets to the data/extra folder. Easiest would just be to add a CSV file like the one which is there already.

**Comment by LaDilettante** [comment]
I'd be happy to contribute. One related issue is that if we allow non-comprehensive custom dicts (e.g. my dictionary wouldn't cover all cities in the world), then `countrycode` should have an option allowing non-match to be kept instead of converted to `NA`.

**Comment by vincentarelbundock** [comment]
Yes. Should be automatic.

**Comment by cjyetman** [comment]
I would be very cautious with automatically returning the original string instead of `<NA>`. That is very different from the standard behavior of this function. For example, consider the example given for the new custom_dict argument on the [README.md](https://github.com/vincentarelbundock/countrycode/blob/master/README.md)...
```r
library(countrycode)
url = "https://raw.githubusercontent.com/vincentarelbundock/countrycode/master/data/extra/us_states.csv"
state_dict = read.csv(url, stringsAsFactors=FALSE)
countrycode(c('MI', 'OH', 'Bad'), 'abbreviation', 'state', custom_dict=state_dict)
```
which currently returns...
```r
[1] "Michigan" "Ohio"     NA
```
but would instead return...
```r
[1] "Michigan" "Ohio"    "Bad"
```
which is probably not what is expected in most use cases

**Comment by vincentarelbundock** [comment]
Oh yeah, sorry, I misread @LaDilettante 's post. @cjyetman is right: we have recently agreed that it was safer to return NA. In any case, it's a one-liner for analysts who want to fill back in the NAs with original strings, so the cost to pay for safety seems pretty low here.

**Comment by cjyetman** [comment]
I can imagine something like a `no_match = NA` argument, which could potentially be set to some other character or character vector. So you could do...
```r
countrycode(c('USA', 'DEU', 'XXX'), 'iso3c', 'country.name')
[1] "United States of America"    "Germany"    NA

countrycode(c('USA', 'DEU', 'XXX'), 'iso3c', 'country.name', no_match = '')
[1] "United States of America"    "Germany"    ""

myisos <- c('USA', 'DEU', 'XXX')
countrycode(myisos, 'iso3c', 'country.name', no_match = myisos)
[1] "United States of America"    "Germany"    "XXX"
```

**Comment by vincentarelbundock** [comment]
`x[is.na(x)] = y[is.na(x)]`

Doesn't seem so bad to me. (drawing on my change-averse roots here :))

**Comment by vincentarelbundock** [comment]
@LaDilettante I'm closing this, but feel free to open a new issue or PR when you're set to add new dictionaries.

also, you might want to take a look at what we're doing over at: https://github.com/vincentarelbundock/countryyear

Basically, if you're scrapping info from some source, it would be nice to get a copy of the scrapping-cleaning script you use.

Thanks again for your interesting in this project!
