### ISSUE TITLE
document procedure for contributing custom dictionaries

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#125]
I realize it may be overly optimistic to think that many people are going to be submitting custom dictionaries or other contributions, but we could head off some discussions/questions by preemptively determining the necessary parameters for an acceptable submission/PR and documenting that somewhere easy, like in the [README.md](https://github.com/vincentarelbundock/countrycode/blob/master/README.md), or in a CONTRIBUTIONS.md, or in a [wiki page](https://github.com/vincentarelbundock/countrycode/wiki). Then if anyone ever asks, you can just point them there and close the issue.

here's a few for examples to get started...
- should look something like [data/extra/us_states.csv](https://github.com/vincentarelbundock/countrycode/blob/master/data/extra/us_states.csv)
- should have unique purpose (not overlapping with existing custom dictionaries)
- should conform to [RFC 4180 CSV standard](https://tools.ietf.org/html/rfc4180) (e.g. comma-delimited, etc.)
- UTF-8 encoding
- should have concise, sensible, valid (in the R data frame sense) column header names
- clean PR submitted with no other files or changes included

**Comment by vincentarelbundock** [comment]
Sounds great. I would prefer README.md as it is most visible, followed by CONTRIBUTIONS.md, since it doesn't rely on github wikis and the repo would still be self-contained.

What are the most salient features of RFC 4180? Maybe we can give an example command for `write.csv` with flags which should generally produce clean CSV.

**Comment by cjyetman** [comment]
- **comma** separated: not semi-colon, not tab, not pipe, not fixed-width
- fields are optionally enclosed in double quotes; double quote inside of double quotes must be escaped with a preceding double quote e.g. """Democratic"" People's Republic of Korea"
- if a field has a comma in it, it must be enclosed in double quotes, e.g. "Palestine, State of"
- `<NA>`/blank fields are blank, not the string 'NA' (not RFC 4180, but important here because of Namibia)

using base `write.csv`
```r
write.csv(custom_dict, 'custom_dict.csv', quote = TRUE, na = '', row.names = FALSE, qmethod = 'double', fileEncoding = 'UTF-8')
```
using Hadley's [`readr`](https://github.com/tidyverse/readr)
```r
readr::write_csv(custom_dict, 'custom_dict.csv', na = '')
```

**Comment by vincentarelbundock** [comment]
b979648
