### ISSUE TITLE
no_match argument

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#126]
As discussed beginning [here](https://github.com/vincentarelbundock/countrycode/issues/123#issuecomment-276465961)...

Consider adding a `no_match` argument that would be set to NA as default to maintain existing behavior, but which could potentially be set to some other value or vector of values that would be returned in the case that no match is found.

## Examples

existing behavior
```r
countrycode(c('USA', 'DEU', 'XXX'), 'iso3c', 'country.name')
[1] "United States of America"    "Germany"    NA
```

returning a blank string instead of `<NA>`
```r
countrycode(c('USA', 'DEU', 'XXX'), 'iso3c', 'country.name', no_match = '')
[1] "United States of America"    "Germany"    ""
```

returning a string identifier for unmatched values
```r
countrycode(c('USA', 'DEU', 'XXX'), 'iso3c', 'country.name', no_match = 'UNKNOWN')
[1] "United States of America"    "Germany"    "UNKNOWN"
```

returning the original, unmodified value if no match is found
```r
myisos <- c('USA', 'DEU', 'XXX')
countrycode(myisos, 'iso3c', 'country.name', no_match = myisos)
[1] "United States of America"    "Germany"    "XXX"
```

## Implementation notes
- the class of `no_match` should be the same as the `destination` code
- `no_match` should be the same length as `destination_vector`; if `length(no_match)` equals 1, the single value can be repeated to make it the same length with `no_macth <- rep(no_macth, length(sourcevar)`
- easy to implement post-matching with `destination_vector[is.na(destination_vector)] <- no_match[is.na(destination_vector)]`

**Comment by vincentarelbundock** [comment]
As previously discussed, I don't really think this is useful.

That said, it's a pretty simple tweak, so if you insist I guess we can do this.

**Comment by cjyetman** [comment]
Don't hold anything up for it. Just putting it here because I may have some time to throw it together sometime in the near future.

**Comment by vincentarelbundock** [comment]
sounds good. I think I'll have time to package for CRAN today or tomorrow.

**Comment by LaDilettante** [comment]
I think this argument makes the intention abundantly clear. The one-liner `x[is.na(x)] = y[is.na(x)]` works fine, but the intention isn't clear to the reader of the code.

For the reader to understand why we fix the NA like that, they must understand countrycode's behavior of returning NA for non-match.

**Comment by vincentarelbundock** [comment]
Makes sense.

**Comment by vincentarelbundock** [comment]
For reference, this was implemented here: https://github.com/vincentarelbundock/countrycode/commit/565d171a5b3da4ac98f39ef7c517afe4929f62df
