### ISSUE TITLE
New numbering scheme

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#129]
Currently we have:

0.1 -> 0.2 -> ... -> 0.19

Ugly, no? 

After 1.0, we should probably go for 1.01 -> 1.02, etc.

**Comment by cjyetman** [comment]
The most common versioning scheme that I'm aware of, [semantic versioning](http://semver.org), prohibits leading zeros in version numbers. Of course, it's only a matter of opinion... most important is to have a defined scheme that you stick to.

**Comment by vincentarelbundock** [comment]
Nah, this looks good to me. Basically, this would just require I add a .0 to the current scheme (and increment the last bit for patches). Seems straightforward enough.

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countrycode/commit/36ed55dd4bdeac53f075bc8d3f2d70ea2aa925f2
