### ISSUE TITLE
Regex: Catch countries in middle of sentence

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#135]
A similar problem was brought up by @cjyetman with the new Ireland regex: https://github.com/vincentarelbundock/countrycode/pull/134
 
```
f = function(k) gsub('COUNTRY', k, 'The governement of COUNTRY was reelected.')
origin = countrycode_data$country.name.en
sentence = sapply(origin, f)
target = countrycode(sentence, 'country.name', 'country.name')
origin[is.na(target)]
```

Looks like these regexes suffer from similar problems:

- "Federal Republic of Germany" 
- "Ireland"                    
- "Republic of Vietnam"

**Comment by vincentarelbundock** [comment]
Added a quick and dirty test to catch this issue: 919ee6a

**Comment by cjyetman** [comment]
I like that test, if we intend to match with strings like that... which I think is more relevant now that we return `<NA>` for multiple matches, so that...
```r
countrycode('report from Canada and the United States', 'country.name', 'country.name')
[1] NA
countrycode('report from the United States', 'country.name', 'country.name')
[1] United States
```

**Comment by vincentarelbundock** [comment]
I like the double match test: c553195

**Comment by vincentarelbundock** [comment]
f70546a
and
https://github.com/vincentarelbundock/countrycode/commit/db1d88f09dea4864ba7a43855042c04f27ae27e6
allow us to close this
