### ISSUE TITLE
"country.name" code stopped working since 0.19

### ISSUE THREAD

**Issue by hideaki** [vincentarelbundock/countrycode#138]
With 0.19, I'm seeing following errors when using "country.name" code.
It works with 0.18.

```
> countrycode(740,"cown","country.name")
Error in countrycode(740, "cown", "country.name") : 
  Destination code not supported
> countrycode('Albania', 'country.name', 'iso3c')
Error in countrycode("Albania", "country.name", "iso3c") : 
  Origin code not supported
> 
```

**Comment by vincentarelbundock** [comment]
That's really weird. I can't replicate it locally, even after removing and re-installing directly from CRAN.

```
> remove.packages('countrycode')
> install.packages('countrycode')
> library(countrycode)
> countrycode('Albania', 'country.name', 'iso3c')
[1] "ALB"
countrycode(740,"cown","country.name")
> countrycode(740,"cown","country.name")
[1] "Japan"
```

Does the Github version work for you?

**Comment by cjyetman** [comment]
Can you run the following code and paste the results here...
'''r
Sys.getlocale()
Sys.info()
sessionInfo()
'''

**Comment by hideaki** [comment]
It seems that I just can't reproduce this any more.
Let me close this once, and if I find a way to reproduce it, I will reopen it.

**Comment by vincentarelbundock** [comment]
thanks!
