### ISSUE TITLE
"Stuff happens in North Korea" does not match unambiguously

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#139]
as reported [here](http://stackoverflow.com/questions/42235490/from-string-to-regex-to-new-string)

Need to check regexes for North Korea and South Korea. This is probably due to the North Korea regex not allowing anything but whitespace before 'North'

**Comment by vincentarelbundock** [comment]
Test: 1d27025

**Comment by vincentarelbundock** [comment]
@ulfelder Your stackoverflow problem should now be fixed in Github master: https://github.com/vincentarelbundock/countrycode/commit/fa953530855620cb7fdbc2572d44dc8fcdd203f1

You can now use countrycode directly to convert sentences to country codes:

```
> library(devtools)
> install_github('vincentarelbundock/countrycode')
> library(countrycode)
> df <- data.frame(string = c("Russia is cool (2015) ",
+                             "I like - China",
+                             "Stuff happens in North Korea"),
+                  stringsAsFactors = FALSE)
> df$iso3c = countrycode(df$string, 'country.name', 'iso3c')
> df
                        string iso3c
1       Russia is cool (2015)    RUS
2               I like - China   CHN
3 Stuff happens in North Korea   PRK

```

**Comment by luispfonseca** [comment]
Not exactly the same issue, but found with real data:

``` R
library(countrycode)
> countrycode("Korea, Dem. Rep.", origin = "country.name", dest = "country.name")
[1] "South Korea"
```

**Comment by cjyetman** [comment]
@luispfonseca if/when issues like #164 (adding common abbreviations to the regexes) gets resolved, "Korea, Dem. Rep." may be recognized as North Korea
