### ISSUE TITLE
CS still returned for Czechoslovakia instead of SK,CZ

### ISSUE THREAD

**Issue by PhillRob** [vincentarelbundock/countrycode#143]
Not sure what the common handle is for changes in sovereignty. Should querying for countries that no longer exist return the current code(s) of the current country(ies)?

**Comment by cjyetman** [comment]
'Czechoslovakia' is not a valid name for Czechia nor Slovakia, so countrycode will not return either of their ISO codes nor some kind of compound version of their ISO codes. Rather, it returns what was most recently the valid ISO code for Czechoslovakia.
