### ISSUE TITLE
leading zeros in iso3n

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#145]
Should the iso3n destination code return a string with leading zeros rather than a numeric? ISO refers to it as a "three digit numeric code (numeric -3)" [here](https://www.iso.org/iso-3166-country-codes.html). I just ran into an issue where a shapefile referenced countries by iso3n with leading zeros and the data I exported was using a numeric version of iso3n (without leading zeros, obviously).

I'm not opinionated about the issue, just thought I drop it here for discussion.

**Comment by vincentarelbundock** [comment]
I lean toward keeping it as digits for two reasons.

1. Backward compatibility
2. Most readers (read_csv) will autodetect the column as numeric, so my intuition (based on no fact) is that users will most often encounter iso3n as integers.
