### ISSUE TITLE
Sudan iso3n should be 729

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#146]
At the moment, countrycode returns 736, which was the code before South Sudan split off. Alpha-codes remained the same.

**Comment by vincentarelbundock** [comment]
Thanks!

https://github.com/vincentarelbundock/countrycode/commit/5ba7c797834a67c69c5a592274f211f590dc3a90

```
> countrycode("Sudan", 'country.name', 'iso3n')
[1] 729
```
