### ISSUE TITLE
``return_na`` argument

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#147]
When ``return_na = FALSE`` and ``countrycode`` fails to find a proper match, it tries to fill-in the destination vector with values of the origin vector (provided they are both of the same class).

https://github.com/vincentarelbundock/countrycode/commit/730896901878ec6435626ac5fc1465fdf66591da

Leaving this here in case anyone cares to comment on the argument name or anything else.

**Comment by cjyetman** [comment]
Conceptually, this is similar to what's proposed in #126... do something different than return NA. The other is much more flexible, but this is a much more clear way of returning the origin. Maybe there's a way to merge the ideas? Probably does not make sense to have both.

**Comment by cjyetman** [comment]
Btw... I know you never liked that idea so much, so... not pushing, just pointing out the overlap

**Comment by vincentarelbundock** [comment]
Yeah yeah. For some reason, I couldn't find the original issue. 

I got another email asking for this functionality, so I'm just giving in to overwhelming consumer demand :)

How about we return the original vector values if ``nomatch == NULL``?

**Comment by cjyetman** [comment]
Brilliant! I like that solution.

**Comment by vincentarelbundock** [comment]
Great. Implemented here: https://github.com/vincentarelbundock/countrycode/commit/565d171a5b3da4ac98f39ef7c517afe4929f62df
