### ISSUE TITLE
add CLDR country names to data/extra

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#148]
I briefly spoke to @alistaire47 about his [`passport`](https://github.com/alistaire47/passport) package, which has a lot of overlap with `countrycode`. One of this motivations was to get "better" standardized country names. The primary set of country names used in `passport` is the set from the CLDR (Common Locale Data Repository Project) project of the Unicode Consortium. They have country names in many different languages and language/country variations. The stated [goal](http://cldr.unicode.org/translation/country-names#TOC-Customary-Names) is "the most customary name used in your language, even if it is not the official name".

I suspect @vincentarelbundock won't want to change the default country names in `countrycode`, nor add 500+ language variations to the default dictionary in `countrycode`, but I think CLDR's "most customary" names plus the many language variants might be useful to enough people to warrant putting them in the [`data/extras`](https://github.com/vincentarelbundock/countrycode/tree/master/data/extra) directory, and possibly modifying the documentation to be a bit more explicit about how to use it.

here's some code to build a custom dictionary using the full CLDR set in JSON from [their Github page](https://github.com/unicode-cldr/cldr-localenames-full)...
```r
library(jsonlite)
library(curl)
library(dplyr)
library(countrycode)
library(readr)

full_url <- 'https://api.github.com/repos/unicode-cldr/cldr-localenames-full/releases/latest'
full_zip_url <- jsonlite::fromJSON(full_url)$zipball_url
zipfile <- curl::curl_download(full_zip_url, tempfile())

filelist <- unzip(zipfile, list = T)
filelist <- filelist$Name[grep('/territories.json$', filelist$Name)]
filelist <- unzip(zipfile, files = filelist, overwrite = T, exdir = tempdir())

cldr_countrynames <- countrycode::countrycode_data

for (file in filelist) {
  lang <- jsonlite::fromJSON(file)
  lang <- lang[[1]][[1]]$localeDisplayNames$territories
  lang <- data.frame(names(lang), unlist(lang), stringsAsFactors = F)
  names(lang) <- c('iso2c', paste0('cldr.full.', rev(strsplit(file, '/')[[1]])[2]))
  cldr_countrynames <- dplyr::left_join(cldr_countrynames, lang)
}

unlink(filelist)
unlink(zipfile)

readr::write_csv(cldr_countrynames, 'cldr_full.csv', na = '')
```

and if the custom dictionary were committed to the `countrycode` repo, then something like this would be possible...
```r
cldr_full <- readr::read_csv('https://raw.githubusercontent.com/vincentarelbundock/countrycode/master/data/extra/cldr_full.csv')
countries <- c('USA', 'Macedonia', 'Congo', 'South Korea')
countrycode::countrycode(countries, 'country.name', 'country.name')
countrycode::countrycode(countries, 'country.name.en.regex', 'cldr.full.en-US-POSIX', custom_dict = cldr_full, origin_regex = TRUE)
countrycode::countrycode(countries, 'country.name.en.regex', 'cldr.full.ta-MY', custom_dict = cldr_full, origin_regex = TRUE)

```

**Comment by cjyetman** [comment]
then would you prefer the scraper code over in `countryyear`?

**Comment by vincentarelbundock** [comment]
Sure

**Comment by cjyetman** [comment]
moved this over here: vincentarelbundock/countryyear#21
