### ISSUE TITLE
continent conventions

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#150]
- World Bank
- United Nations Statistics Division (5 continents plus Antartica; 17 sub-continents plus Antartica)
- Gazetteer of Planetary Nomenclature: https://planetarynames.wr.usgs.gov/Abbreviations
- https://unstats.un.org/unsd/methodology/m49/

**Comment by emilBeBri** [comment]
I have coded this from the m49 standard stated in the link. I don't know how to add it to the code, but here is the excel-sheet with the conversion table:

**Comment by vincentarelbundock** [comment]
Thanks, but I think it's better to build from source with a scraper.

**Comment by emilBeBri** [comment]
of course, that makes sense.

**Comment by vincentarelbundock** [comment]
These are now officially supported with scraper from original source. Sorry it took so long!

https://github.com/vincentarelbundock/countrycode/pull/228
