### ISSUE TITLE
post-countryyear merge discussion.

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#156]
@cjyetman 

I merged the countryyear repo into master countrycode. The tests all pass (except those related to open/known GH issues).

What do you think of:

* renaming ``countrycode_data`` to ``codelist``.
* asking users to type ?codelist to get the list of codes instead of printing it direction in the `?countrycode` docs. This will make maintaining the package easier, since codes are only listed in the codelist data.frame file.

I'm planning to dog food this for a while before releasing to CRAN, but it should work as intended right now.

Also, I'm not sure if I should write a helper function for ``codelist_panel``. Seems like the main usage will be for users to left-join data in there. That's what we recommend now in the note at the bottom of `?countrycode`.

**Comment by vincentarelbundock** [comment]
https://github.com/alistaire47 FYI, ``countrycode`` now uses CLDR names by default and allows conversion to any variant.

**Comment by vincentarelbundock** [comment]
```
> library(countrycode)
> countrycode('United States of America', 'country.name', 'cldr.short.en')
[1] "US"
```

**Comment by cjyetman** [comment]
I think renaming `countrycode_data` to `codelist`(other than possibly breaking some older code that may have directly referenced it) is fine... but I'll be using it also in the days/weeks to come, so I'll let you know if I think of any negatives.

Dealing with `codelist_panel`... I think there could/should be an easier way, but I don't have any specific solutions to that at the moment. Maybe some kind of helper function could get added on in the future? I suspect that this one sentence about "left-merge"-ing will not be enough for some users.

**Comment by vincentarelbundock** [comment]
You're right.

I tried to improve the note here: https://github.com/vincentarelbundock/countrycode/commit/1d2cd826a954313a70e22a69085b7efcc8c97747

But this is something we can improve over time as we get feedback from users. I suspect it's only the power users anyway who care about such things, and those people will understand the note.

**Comment by vincentarelbundock** [comment]
BTW @cjyetman do you want write access here? (no pressure)

**Comment by cjyetman** [comment]
I don't really need it, unless you want me to help manage (close) issues. Otherwise, I prefer doing PR's anyway... less chance of me being solely responsible for a screw up ;-)

**Comment by cjyetman** [comment]
I guess it wouldn't be bad to have a backup admin here 😄

**Comment by vincentarelbundock** [comment]
Nah, that's fine. Closing issues is not a big deal, and I'm happy to review and merge everything. Just wanted to signal trust and (implicit) ownership :)

**Comment by cjyetman** [comment]
Just for fun, I searched for ["countrycode_data" in R code on Github](https://github.com/search?q=countrycode_data+language%3AR&type=Code&utf8=✓), and there are 142 results, though many are multiple hits from a single repository. There are only a few where the package or the developer is immediately recognizable to me...

https://github.com/ropensci/rdopa
https://github.com/ALShum/rwunderground
https://github.com/fsolt/swiid
https://github.com/rOpenGov/psData
https://github.com/wikimedia/wikimedia-discovery-prince

It's probably not a big deal, just thought I'd check how widespread it is to use the data directly (specifically with that name).

**Comment by vincentarelbundock** [comment]
Clever.

Is there some kind of lazyeval alias function in R we could use?

**Comment by cjyetman** [comment]
Would you mind a PR where I add myself as a contributor to the DESCRIPTION file?

**Comment by vincentarelbundock** [comment]
Please do!
