### ISSUE TITLE
New code: ccTLD - Internet Country Code

### ISSUE THREAD

**Issue by jroberayalas** [vincentarelbundock/countrycode#157]
Hi!

Quick question: does this package also deal with the 2-letter internet country code?

**Comment by vincentarelbundock** [comment]
Not yet, but it would be trivial to add. Do you have an official.source we can scrape?

**Comment by vincentarelbundock** [comment]
Not yet, but it would be trivial to add. Do you have an official.source we can scrape?

**Comment by cjyetman** [comment]
IANA's top level domains?

**Comment by jroberayalas** [comment]
This is the site I was using to check for the codes: http://www.worldstandards.eu/other/tlds/

**Comment by cjyetman** [comment]
in terms of 'official' source for this...

https://www.iana.org/domains/root/db would be a nightmare to parse (lists the responsible organization, not the associated country)

and [this machine readable list to TLDs](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) is just a list, nothing about what they're associated with

**Comment by cjyetman** [comment]
I sent an email to IANA asking where we can get a comprehensive, machine readable list of ccTLD with the associated country. Will update when I get a response.

**Comment by cjyetman** [comment]
so much for an 'official' source...

"Thank you for reaching out to us. 

Unfortunately, we do not have the data you requested available. We are
in the process of reviewing our options on providing this list and we 
have noted your input in having this feature restored in the future. 

We apologize for the inconvenience. Please feel free to let us know if 
you have more questions. "

**Comment by cjyetman** [comment]
In lieu of an "official" source, I created a scraper for the [Wikipedia list of Country code top-level domains](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#Country_code_top-level_domains)...

```r
library(xml2)
library(rvest)
library(dplyr)
library(countrycode)

url <- paste0('https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains')

read_html(url) %>% 
  html_nodes(xpath = '//h2[span[@id = "Country_code_top-level_domains"]]/following-sibling::h2[1]/preceding-sibling::table[contains(@class, "wikitable")][preceding-sibling::h2[span[@id = "Country_code_top-level_domains"]]]') %>% 
  html_table() %>% 
  lapply(function(df) { select(df, Name, Entity) }) %>% 
  bind_rows() %>% 
  select(cctld = Name, cctld.name = Entity) %>% 
  mutate(country.name.en.regex = countrycode(cctld.name, 'country.name', 'country.name.en.regex')) %>% 
  filter(!is.na(country.name.en.regex))
```

**Comment by cjyetman** [comment]
I haven't fully wrapped my head around the new build process, but I finally put together a scraper for this that uses only the original source for input, with the assumption that they are [based on iso2c with few exceptions](https://en.wikipedia.org/wiki/Country_code_top-level_domain#Relation_to_ISO_3166-1). In the rare case that they do not match an iso2c (after removing a few known obsolete/retired/irrelevant ones), it digs deeper by going to the ccTLD Manager's subpage and extracts the country from the address (only necessary for .uk currently).

```
library(xml2)
library(rvest)
library(purrr)
library(dplyr)
library(countrycode)
library(readr)

url <- 'https://www.iana.org/domains/root/db'

dig_deeper <-
  function(.data) {
    country.name <- .data$country.name
    unmatched <- which(is.na(.data$country.name))

    country.name[unmatched] <-
      sapply(unmatched, function(i) {
        read_html(paste0(url, '/', sub('^\\.', '', .data$Domain[i]), '.html')) %>%
          html_node(xpath = '//*[(@id = "main_right")]/h2[2]/preceding-sibling::text()[1]') %>%
          html_text() %>%
          trimws()
      })

    country.name
  }

read_html(url) %>%
  html_table() %>%
  purrr::pluck(1) %>%
  as_tibble() %>%
  filter(Type == 'country-code') %>%  # only keep TLDs that are for countries
  filter(Encoding(Domain) != 'UTF-8') %>%  # don't keep TLD's that are in UTF-8
  filter(`TLD Manager` != 'Retired') %>%  # don't keep retired TLDs
  filter(Domain != '.eu') %>%  # don't keep the EU's TLD
  filter(Domain != '.su') %>%  # don't keep the obsolete TLD for Soviet Union
  filter(Domain != '.ac') %>%  # don't keep Ascension Island's TLD
  filter(!grepl('^Reserved', `TLD Manager`)) %>%  # don't keep reserved TLDs (.gb)
  mutate(country.name = countrycode(sub('^\\.', '', Domain), 'iso2c', 'country.name', warn = FALSE)) %>%
  mutate(country.name = dig_deeperer(.data)) %>%
  filter(!is.na(country.name)) %>%
  select(country.name, ccTLD = Domain) %>%
  write_csv('dictionary/data_ccTLD.csv', na = '')
```

**Comment by NilsEnevoldsen** [comment]
I added a pull request with @cjyetman's code. Feel free to close this pull request and re-do it in your own name if you want.

I made one meaningful change, which is to change the code name to lowercase (`cctld` instead of `ccTLD`).

The codes currently include periods, i.e. `.us` instead of `us`. Is this desirable?

@cjyetman, the build process is to create `get_foo.R`, run it (creating `data_foo.csv`), then run `build.R`. (In addition to optionally adding the code as a valid origin in `countrycode.R`, updating the `NEWS`, updating documentation in `codelist.R`, and running `devtools::document()`.) The `get_foo.R` functions are invoked manually.

**Comment by cjyetman** [comment]
You can merge it if/when it's ready. I'm not counting PRs ;-) You can give me a nod in the News if you want.

I'm not sure about the dot... IANA lists them with the dot, so that gives the impression that the dot is officially part of it. If you wanted to append a TLD to a domain, you would need the dot. But I can also see the point of view that the dot is "syntactic sugar", and I also believe some/many domain name parser would return just the letters if you asked for the TLD. So, I think it's debatable.
