### ISSUE TITLE
Wrong mapping from country to eurocontrol_statfor

### ISSUE THREAD

**Issue by sthonnard** [vincentarelbundock/countrycode#165]
Hello,

According to page 61 of chapter "Traffic regions" from EUROCONTROL SEVEN-YEAR FORECAST FEBRUARY 2017 available at http://www.eurocontrol.int/sites/default/files/content/documents/official-documents/forecasts/seven-year-flights-service-units-forecast-2017-2023-Feb2017.pdf, Russia (ICAO country code UR) is Other Europe and not Asia/Pacific.

> print(countrycode(sourcevar='RU', origin="iso2c", destination="eurocontrol_statfor"))
[1] "Asia/Pacific"

**Comment by vincentarelbundock** [comment]
Thanks for the report! I fixed it.
I'm not planning to release a new version to CRAN very soon, because I made lots of changes to countrycode, and those need to be tested out a bit more before an official release. However, you can install the fixed version right away from github:

```
library(devtools)
install_github('vincentarelbundock/countrycode')
```
