### ISSUE TITLE
ignore case when matching custom origin codes

### ISSUE THREAD

**Issue by matt-jay** [vincentarelbundock/countrycode#166]
Hi!

I am trying to override some of the values returned when using `country.name.en` as destination.

I tried this based on the example provided in the documentation (https://github.com/vincentarelbundock/countrycode#custom-country-match-vector):

```
country_names <- c('gb', 'it')
custom_match <- c(gb = 'Great Britain')
countrycode(country_names, 'iso2c', 'country.name.en', custom_match = custom_match)
```

However, the returned value for country code `gb` is not being overridden by what's provided in `custom_match`.

What am I doing wrong?

**Comment by cjyetman** [comment]
iso2c codes are technically uppercase, so this should work...
```r
country_names <- c('gb', 'it')
custom_match <- c(GB = 'Great Britain')
countrycode(country_names, 'iso2c', 'country.name.en', custom_match = custom_match)
```
but ignoring case when matching custom origin codes is a worthy feature to add

**Comment by matt-jay** [comment]
Yup, just discovered that a moment ago myself. Uppercase is required in custom match definitions. Thanks!

**Comment by cjyetman** [comment]
I'm gonna reopen this as an potential improvement (ignoring case when matching custom origin codes).

**Comment by vincentarelbundock** [comment]
In the spirit of this discussion, I think that silent pre-processing should be very minimal. Closing this. If someone has a very strong case for re-opening, they can file a new issue.
