### ISSUE TITLE
incorrect iso3c conversion

### ISSUE THREAD

**Issue by dipangkar** [vincentarelbundock/countrycode#167]
Following code converts "Ireland (Northern)" to "IRL", which incorrect, "Ireland (Northern)" does not have ISO and it should be converted to GBR (Great Britain). There are few more examples like this.
Is there any thought about this?

 countrycode("Ireland (Northern)", "country.name", "iso3c")

**Comment by vincentarelbundock** [comment]
The latest version of countrycode does not behave as you describe:

```
library(devtools)
install_github('vincentarelbundock/countrycode')
library(countrycode)
countrycode("Ireland (Northern)", "country.name", "iso3c")
[1] NA
```

If you want to supplement codes for non-sovereign countries, I recommend you use the ``custom_match`` argument or build a ``custom_dict``.

Also, see this issue: https://github.com/vincentarelbundock/countrycode/issues/168
