### ISSUE TITLE
CRAN release of the latest version

### ISSUE THREAD

**Issue by nevrome** [vincentarelbundock/countrycode#173]
Thanks for this great data package! I'm really glad you created this!

I realized that the data.frame with the the country codes is called `codefile` in the development version but `countrycode_data` in the CRAN release version.  Can we expect a new CRAN release where this name is stable? I would like to use the file in my package and need a reliable name to reference it.

**Comment by vincentarelbundock** [comment]
Yes. This is going to be a rather big jump to 1.0, and I expect the name to remain stable after that.

How soon do you need this. I might try to release it this week if @cjyetman doesn't have more to put in. (we can also release a major one now, and a smaller one later).

**Comment by nevrome** [comment]
You're awesome! For me it would be perfect to have a stable release at the beginning of march. But: No pressure.

**Comment by cjyetman** [comment]
I don't have any major plans, just minor fixes, so... probably doesn't make sense to hold up a major release for anything I'm considering. (assuming you've either scrapped or mothballed the ideas in #161... that stuff surely would require further testing before it could be considered "stable")

**Comment by vincentarelbundock** [comment]
Right, haven't thought about #161 seriously, so probably not worth holding back for this. I'd like to implement eventually (at least some minimalist version), so I'll keep the code around for inspiration.

**Comment by vincentarelbundock** [comment]
I submitted the package as 1.00.0 to CRAN. Hopefully things go through smoothly, and the package becomes available to everyone soon.

Thanks a ton to @cjyetman who did amazing work on this big new release.
