### ISSUE TITLE
Would you be interested in integrating the M49 country classification scheme from the UN? I

### ISSUE THREAD

**Issue by emilBeBri** [vincentarelbundock/countrycode#178]
Hi,

I just coded the M49 country classification scheme from the UNs Statistics office,  using the ISO-alpha3 letters for countries, which I believe should 
make it fairly straightforward for you to integrate it in this package? Would you be interested in that? 

If so, I'll be happy to deliver it!

link to the schemes main site:
https://unstats.un.org/unsd/methodology/m49/

**Comment by vincentarelbundock** [comment]
That would be great!

Would it be easy to write a function that scrapes it directly from the website (e.g. using `rvest`)?

Check out the dictionary folder for some examples.

**Comment by cjyetman** [comment]
This is basically the same as the existing "un" code, no? Though the list at https://unstats.un.org/unsd/methodology/m49/ seems to be more complete (e.g. Antartica and a bunch of islands)

**Comment by vincentarelbundock** [comment]
Compare to this:

https://github.com/vincentarelbundock/countrycode/blob/master/dictionary/get_un.R

**Comment by cjyetman** [comment]
I don't think a scraper ever got written for the "un" codes because it was already included in [dictionary/data_static.csv](https://github.com/vincentarelbundock/countrycode/blob/master/dictionary/data_static.csv)... so probably would be useful

**Comment by emilBeBri** [comment]
Hmm not quite sure... I'm not that into it, but I'm making a dataframe (to create factor levels) so I thought, might as well offer it to your package. I can't write a scraper, but I'll do something else. Be in touch one of these days!

**Comment by cjyetman** [comment]
here's a rough start if anyone's interested in digging into it...
```r
get_m49 <-
  function() {
    library(xml2)
    library(rvest)

    m49 <- read_html("https://unstats.un.org/unsd/methodology/m49/")
    m49 <- html_nodes(m49, "#ENG_COUNTRIES table")
    m49 <- html_table(m49)[[1]]
    names(m49) <- c("country.name", "m49", "iso3c")
    m49 <- m49[m49$iso3c != "",]
    m49$country.name.en.regex <- CountryToRegex(m49$country.name)
    m49$country.name <- NULL
    m49$iso3c <- NULL

    return(m49)
  }
```

**Comment by vincentarelbundock** [comment]
@emilBeBri as @cjyetman intuited, the m49 codes were already covered by `countrycode` under the name `m49`. Your link was very useful, though, since we like to build our dictionary from original sources.

Adapting the code provided by @cjyetman above, I now included a "scraper" to build m49 from sources. I also modified the documentation to clarify that `un` codes are actually m49. You can read the new doc by typing `?codelist` (after installing from github -- i won't make a release for tthis minor change, obviously).

Thanks!

**Comment by vincentarelbundock** [comment]
Also, I renamed `get_un.R` to `get_un_names.R` to clarify matters.

**Comment by emilBeBri** [comment]
Allright, well happy I could help just a little.

I have also made a factor recoding so that the different countries  can be grouped by the M49-standard, in case you are interested. That is, three levels of geographic areas, the largest one being 5 groups: West, Asia & Oceania, Middle East plus, Latin America & the Carribean, Sub-Sarah Africa.

**Comment by vincentarelbundock** [comment]
Thanks.

We already have "continent" and "region". Unless this is an official classification that is widely used, I'm not sure it's worth it.

**Comment by emilBeBri** [comment]
It is an official classification of the M49, not just my own random one! :D 

How widely used it is, I can't say.

**Comment by vincentarelbundock** [comment]
OK. I opened a new issue in case someone has time to put a scraper together. https://github.com/vincentarelbundock/countrycode/issues/181
