### ISSUE TITLE
Journal of Open Source Software

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#183]
The JOSS bills itself as "A developer friendly journal for research software packages." It's peer reviewed, is associated with the Open Source Initiative and NumFOCUS. The papers are super short, and the submission process is extremely straightforward.

http://joss.theoj.org/about

Obviously, this isn't the American Economic Review or the American Political Science Review. Still, I've been thinking about ways to improve recognition of software writing in social science academia. I don't think I'll get much (if any) credit for this at my institution, but just putting something like this on my CV would be a kind of political act...

I had a short exchange with one their Editors on Twitter, and he said that if we can explain that `countrycode` has "research applications" within a couple paragraphs, then the package could fall in-scope of what they publish.

@cjyetman Would you be interested in putting a paper together with me?

Back in the day, @NilsEnevoldsen did a major refactor of all the regexes, and basically created the test suite from scratch. I'd be happy to bring him in too if he's interested.

**Comment by vincentarelbundock** [comment]
twitter thread: https://twitter.com/thosjleeper/status/1015272190164525056

**Comment by NilsEnevoldsen** [comment]
Sure, let me know how things move forward. :smile:

**Comment by vincentarelbundock** [comment]
Wrote a quick first draft and added you both as collaborators on this repo: 

https://github.com/vincentarelbundock/countrycode_joss

Feel free to make any edits you think are appropriate.

But maybe once you read the following paper you'll re-think your participation ;)

https://voxeu.org/article/economists-publications-lists-less-may-be-better

**Comment by vincentarelbundock** [comment]
Excellent!

The nice thing about their "developper-friendly" format, is that there isn't much of a new contribution to make. This is much more about recognizing *past* contributions. Just add your contact info to the header of  `paper.md` and make any changes you want to the text.

If you have an idea for a cooler example, that could be nice too, but not necessary.

**Comment by cjyetman** [comment]
I added my info, and created two issues that you might want to look at.

**Comment by vincentarelbundock** [comment]
The review process happens in the open on github. This is pretty interesting to me. Check it out if you're curious:

https://github.com/openjournals/joss-reviews/issues/838

**Comment by vincentarelbundock** [comment]
@NilsEnevoldsen @cjyetman 

We are now officially co-authors. It's the first time I publish something with people I haven't met or spoken to. Weird, isn't it?

Congrats!

**Comment by vincentarelbundock** [comment]
https://doi.org/10.21105/joss.00848
