### ISSUE TITLE
Interact with ISOcodes package?

### ISSUE THREAD

**Issue by briatte** [vincentarelbundock/countrycode#187]
https://cran.r-project.org/web/packages/ISOcodes/

**Comment by vincentarelbundock** [comment]
Nice! One way to approach this would be to package a bunch of `custom_dict` data.frames, and to write think wrappers around `countrycode`. Essentially,

```
isocode = function(...) {
    countrycode(sourcevar, origin, destination, 
                          custom_dict = countrycode::codelist_iso)
}
```

**Comment by vincentarelbundock** [comment]
The latest version of `countrycode` supports ISO3166 (country codes) and ISO4127 (currencies). 

I added a section to the README to explain how to use the `custom_dict` argument to use the remaining `ISOcodes` data, including the computer encodings character map and the language names. You can find these examples here:

https://github.com/vincentarelbundock/countrycode#custom_dict-the-isocodes-package

**Comment by vincentarelbundock** [comment]
This took a while. Sorry!
