### ISSUE TITLE
Release tag for JOSS version

### ISSUE THREAD

**Issue by andybega** [vincentarelbundock/countrycode#188]
Hello, as fortune would have it I'm reviewing your JOSS submission at https://github.com/openjournals/joss-reviews/issues/848. One very minor issue, would you mind tagging the JOSS version as a release? I see that there is a commit (506291a9d5948f70aae28684134ee5f9413c4eba) for it but this would just make it slightly easier to find in case anyone might want to.

**Comment by vincentarelbundock** [comment]
Thanks a lot for your work at JOSS. This is a great initiative and I really appreciate those who put in the work!

And thanks for the useful suggestion: I a tag: https://github.com/vincentarelbundock/countrycode/releases/tag/joss

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countrycode/releases/tag/1.00.0-joss

cleaner version
