### ISSUE TITLE
add a CITATION file

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#189]
now that there's an official DOI

for reference...
https://cran.r-project.org/doc/manuals/R-exts.html#CITATION-files
http://r-pkgs.had.co.nz/inst.html#inst-citation

http://joss.theoj.org/papers/10.21105/joss.00848 says to cite as:
Arel-Bundock et al., (2018). countrycode: An R package to convert country names and country codes . Journal of Open Source Software, 3(28), 848, https://doi.org/10.21105/joss.00848

**Comment by vincentarelbundock** [comment]
Excellent idea: https://github.com/vincentarelbundock/countrycode/commit/01cd6460be44d53d63a5d93968474fce3f77b292
