### ISSUE TITLE
Panel dictionary build process

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#201]
The latest commits introduce major changes to the dictionary build process. I thought it was important to centralize the building of *panel* data, because choices are interdependent (i.e., they influence which codes get matched to which codes in a given year).

The new system might not be perfect, but I think it works OK:

1. All cross-sectional datasets are still built using `get_*` functions.
2. All panel datasets are downloaded and merged with explicit compatibility choices in `build_panel.R`
3. Scripts like `get_cow_cs.R` take the panel data from build_panel.R, and converts it to a cross-sectional representation.
4. We save a version of the panel-only data as CSV in `dictionary/`

This is all merged in master now, but there are a few issues remaining, so this is not ready to release.

Also note that I finally fixed Travis CI, so the badge actually tells us that testthat tests are broken.

FYI, @cjyetman

**Comment by cjyetman** [comment]
nice! I will take a look at it when I have some more time (probably in a couple weeks)

**Comment by vincentarelbundock** [comment]
I have done what I wanted to do. We can open new issues for specific problems or improvements.
