### ISSUE TITLE
Eswatini

### ISSUE THREAD

**Issue by paycemadden** [vincentarelbundock/countrycode#205]
Please add Eswatini as an alternate country.name for Swaziland. Thanks! :)

**Comment by cjyetman** [comment]
Looks like [Unicode CLDR 35](http://cldr.unicode.org/index/downloads/cldr-35) (which is the basis for the default country names in `countrycode`) was "updated to local equivalents of "North Macedonia" (MK) and "Eswatini" (SZ)" on 2019-03-27... so presumably `countrycode` will pick that up next time the dictionary builder is run.

**Comment by vincentarelbundock** [comment]
Yep, but the download switch would need to be flipped to re-download the CLDR names

**Comment by NilsEnevoldsen** [comment]
Fixed.

```r
> countrycode::countrycode("SZ","iso2c","country.name")
[1] "Eswatini"
```
