### ISSUE TITLE
add UN region codes

### ISSUE THREAD

**Issue by briatte** [vincentarelbundock/countrycode#206]
Might be useful to check or enrich the package?

https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes

> ISO 3166-1 country lists merged with their UN Geoscheme regional codes in ready-to-use JSON, XML, CSV data sets

**Comment by cjyetman** [comment]
Thanks for the suggestion!

`countrycode` already includes the ISO-3166 variants, but we prefer to get them from the original source. Do you know precisely what @lukes means by "note ISO doesn't give away all information for free - so refer to the Wikipedia table (assuming it is mostly kept up to date)"?

The UN regions could be useful, taken from the original source. I think we would have to decide if we want to add another destination only code... there are essentially limitless variations of regional groupings, so we have to make a decision about where to draw the line, based on how useful (and stable) we think a particular regional grouping might be.

The UN region data is coming from https://unstats.un.org/unsd/methodology/m49/overview/

**Comment by briatte** [comment]
Hi @cjyetman 

Thanks for your reply. If `countycode` already uses an official source, then no further checks should be needed. I have no answer re: what @lukes mentions, but perhaps he'll stop by and let us know :)

**Comment by lukes** [comment]
@briatte @cjyetman Thanks for the mention. Unless I'm mistaken https://www.iso.org/iso-3166-country-codes.html doesn't provide the data in an easily downloadable format for free, but rather it asks you to pay.

Also 👍 for R!

**Comment by NilsEnevoldsen** [comment]
I don't have a strong feeling about adding these, but they're easy to scrape. Agree with https://github.com/vincentarelbundock/countrycode/issues/206#issuecomment-495981688 that "there are essentially limitless variations of regional groupings, so we have to make a decision about where to draw the line", but the United Nations seems like a reasonable source.
