### ISSUE TITLE
German country name and regex for Republic of Vietnam is wrong

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#208]
in line 276 of  [data_static.csv](https://github.com/vincentarelbundock/countrycode/blob/master/dictionary/data_static.csv#L276)...

`country.name.de` =  [blank]
`country.name.de.regex` = `ASIA`

for comparison...
`country.name.en` = `Republic of Vietnam`
`country.name.en.regex` = `(?!social).*republic.of.viet.?nam|south.viet.?nam|viet.?nam.south`

e.g.
```r
countrycode("United States of America", "country.name", "country.name.de")
# [1] "Vereinigte Staaten"
> countrycode("Vietnam", "country.name", "country.name.de")
# [1] "Vietnam"
> countrycode("Republic of Vietnam", "country.name", "country.name.de")
# [1] NA
# Warning message:
#   In countrycode("Republic of Vietnam", "country.name", "country.name.de") :
#   Some values were not matched unambiguously: Republic of Vietnam
```

Tests specifically for "Vietnam" and "Republic of Vietnam" and their interaction are probably needed, in multiple languages.

**Comment by vincentarelbundock** [comment]
Consolidating vietnam issues here: https://github.com/vincentarelbundock/countrycode/issues/207
