### ISSUE TITLE
Function to identify closest field

### ISSUE THREAD

**Issue by geotheory** [vincentarelbundock/countrycode#209]
Any interest in wrapping this in?

```
closest_field = function(x){
  if(length(x) > length(unique(x))) stop('x must be a vector of unique values')
  similarity = sapply(codelist, function(field){ 100 * sum(x %in% field) / length(x) })
  similarity = data.frame(field = names(similarity), similarity = as.vector(similarity), stringsAsFactors=FALSE)
  similarity = similarity[order(similarity$similarity, decreasing = TRUE),]
  if(suppressWarnings(suppressMessages(!require(tibble)))) return(similarity)
  return(as_tibble(similarity))
}

closest_field(c('CM','AL','PA','MK','HA','CO','ZI','KU','TH','FI'))
#> # A tibble: 730 x 2
#>    field         similarity
#>    <chr>              <dbl>
#>  1 fips                 100
#>  2 ecb                   70
#>  3 eurostat              70
#>  4 genc2c                70
#>  5 iso2c                 70
#>  6 wb_api2c              70
#>  7 cldr.name.bem         70
#>  8 cldr.name.bo          70
#>  9 cldr.name.cu          70
#> 10 cldr.name.gv          70
#> # … with 720 more rows

closest_field(c('Ivory Coast','Guinea','Iran','Russia','North Korea'))
#> # A tibble: 730 x 2
#>    field              similarity
#>    <chr>                   <dbl>
#>  1 cow.name                  100
#>  2 vdem.name                 100
#>  3 cldr.variant.en           100
#>  4 cldr.variant.en_gb        100
#>  5 country.name.en            80
#>  6 eurostat.name              80
#>  7 p4.name                    80
#>  8 wvs.name                   80
#>  9 cldr.name.en               80
#> 10 cldr.name.en_gb            80
#> # … with 720 more rows
```

**Comment by vincentarelbundock** [comment]
Thanks for the proposal. This is quite interesting. To be honest, I can't really see myself using this (I typically know what data comes in), but if you tell me there are reasonable use cases, I'll take your word for it. A few thoughts:

1. `closest_field` seems a bit non-obvious. Is there a better name we can find? Maybe something like `guess_code`. This would be less "formally correct" since some fields are not actually codes, but it would be consistent with "countrycode" and more self-explanatory. Open to any suggestion or to an argument for `closest_field`.
2. Why a unique vector as input? I guess a typical use-case would be to guess which code a column is in, and there may be duplicate entries in that column. Maybe we should just `unique(origin)` at the start.
3. Would it make sense to start with a type comparison. For example, we know immediately that "CM" is not iso3n, which is numeric.
4. This new function would probably need:
    - Its own separate .R file in the /R folder
    - Roxygen documentation
    - An example in the README

Let me know what you think of all this. To be perfectly honest, I'm way over-committed this summer, so I'm unlikely to implement any of this. But if you bring us close to the goal line, I could finish things up and package for CRAN.

**Comment by cjyetman** [comment]
Can the purpose for this function be described in one, simple sentence? Is it something like... "Determine which of the destination codes in the countrycode package contain the highest percentage of elements in a vector."?

Likewise, I don't really understand the use case for it, but I think if there is one and it can be sufficiently described, why not?

**Comment by geotheory** [comment]
Thanks both. I think @cjyetman is pretty much there. The point is that sometimes open source data contains fields of country names or codes that aren't specified.  If you have such a field that looks like ISO3C, or possibly just a set of country names, it can be some work to figure out which of `codelist`'s considerable selection are appropriate!  This function takes that pain away, at least to some degree of probability.

**Comment by geotheory** [comment]
I think the unique aspect helps to avoid confusion over the similarity metric. But yes I suppose some users might want to preserve the original set in order to decide how much of their actual data is affected by unmatched values. But we can anticipate performance issues for very long vectors, so might need additional logic to narrow the odds.

**Comment by cjyetman** [comment]
In regards to the use of `unique`, I would suggest running the matching on a unique set of the input vector, but not stopping with an error if the input vector has duplicates.... much like how the `countrycode` function works.

**Comment by cjyetman** [comment]
In regards to the functionality, since the *intended* functionality seems to be more along the lines of “Output a list of destination codes that are likely to be what the input vector is composed of.”, I would suggest adapting the function to do precisely that task and nothing else... e.g. there’s probably no reason to report destination codes that match less than 80% or so of the input vector.

**Comment by geotheory** [comment]
Unique point - well yes that would be the blindingly obvious solution I didn't think of.

80% threshold sounds sensible - I guess variablised so user can override.

**Comment by geotheory** [comment]
Feels like it got a bit complicated.

```
guess_field <- function(x, min_similarity = 80){
  x_orig = x
  if(length(x) > length(unique(x))) x = unique(x)
  matching_values = lapply(codelist, function(field){ x[x %in% field] })
  similarity <- sapply(matching_values, function(field_matches){ 100 * length(field_matches) / length(x) })
  similarity <- data.frame(field = names(similarity), uniques_matched = as.vector(similarity), stringsAsFactors=FALSE)
  similarity <- similarity[order(similarity$uniques_matched, decreasing = TRUE),]
  similarity <- similarity[similarity$uniques_matched >= min_similarity,]
  # list unmatched values
  if(any(similarity$uniques_matched < 100)){
    similarity$unmatched_values = sapply(codelist[,similarity$field], function(field){ paste(x[!x %in% field], collapse='; ') })
    similarity$unmatched_values[similarity$unmatched_values == ''] = NA_character_
  }
  # account for non-unique input
  if(length(x) < length(x_orig)){
    similarity$x_matched <- sapply(matching_values[similarity$field], function(matches){ 100*sum(x_orig %in% matches) / length(x_orig) })
    similarity = similarity[,c(1,2,4,3)]
  }
  if(suppressWarnings(suppressMessages(!require(tibble)))) return(similarity)
  as_tibble(similarity)
}

guess_field(c('CM','AL','PA','MK','HA','CO','ZI','KU','TH','FI'))
#> # A tibble: 1 x 2
#>   field uniques_matched
#>   <chr>           <dbl>
#> 1 fips              100

guess_field(c('Guinea','Iran','Russia','North Korea',rep('Ivory Coast',50),'Scotland'))
#> # A tibble: 4 x 4
#>   field              uniques_matched x_matched unmatched_values
#>   <chr>                        <dbl>     <dbl> <chr>           
#> 1 cow.name                      83.3      98.2 Scotland        
#> 2 vdem.name                     83.3      98.2 Scotland        
#> 3 cldr.variant.en               83.3      98.2 Scotland        
#> 4 cldr.variant.en_gb            83.3      98.2 Scotland
```

**Comment by cjyetman** [comment]
Here's my go at it...

```r
guess_field <- function(x, min_similarity = 80) {
  x <- unique(x)
  
  match_percentage <-
    sapply(countrycode::codelist, function(code) {
      sum(x %in% code) / length(x) * 100
    })
  
  match_percentage <- match_percentage[match_percentage >= min_similarity]
  
  match_percentage <- match_percentage[order(match_percentage, decreasing = TRUE)]
  
  data.frame(code = names(match_percentage), 
             percent_of_unique_matched = match_percentage,
             stringsAsFactors = FALSE)
}

guess_field(c('CM','AL','PA','MK','HA','CO','ZI','KU','TH','FI'))
# # A tibble: 1 x 2
#   code  percent_of_unique_matched
#   <chr>                     <dbl>
# 1 fips                        100

guess_field(c('Guinea','Iran','Russia','North Korea',rep('Ivory Coast',50),'Scotland'))
# # A tibble: 4 x 2
#   code               percent_of_unique_matched
#   <chr>                                  <dbl>
# 1 cow.name                                83.3
# 2 vdem.name                               83.3
# 3 cldr.variant.en                         83.3
# 4 cldr.variant.en_gb                      83.3
```

**Comment by geotheory** [comment]
Simpler than mine for sure!  I have no strong view tbh :)

**Comment by vincentarelbundock** [comment]
I finally added the `guess_field`. Was indecisive, but @cjyetman function is so simple that it should be easy to maintain.

34b190e2a
