### ISSUE TITLE
use GitHub Actions to test scrapers periodically

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#212]
I've been playing with the newly released GitHub Actions, and I think it would be really cool to use it to automatically test the dictionary build process periodically and report if any changes have occurred. I setup a basic demonstration on a private fork [here](https://github.com/cjyetman/countrycode).

The action file is here: https://github.com/cjyetman/countrycode/blob/master/.github/workflows/scraper_test.yml

The scraper tester script is here: https://github.com/cjyetman/countrycode/blob/master/dictionary/test_scrapers.R

and the first results from an auto run are here (you can see the relevant results under the "run Scraper test" section): https://github.com/cjyetman/countrycode/commit/9b4b8766d36783d2967127941bda0c1ad310d66a/checks?check_suite_id=313706325

This example runs automatically every 3 months and also any time a push is committed to master, but obviously that could be changed to whatever is appropriate. Additionally, this could probably get to the point of auto-creating an issue whenever it detects a change, or even create a PR with the changes in the long run.

@vincentarelbundock do you think this is something worth investing time in?

**Comment by vincentarelbundock** [comment]
Oh that's very cool! (Incidentally, it's useful to know that some scrapers no longer work.)

It would be very nice to have that, but as always, this is supposed to be a "fun" project. Just make sure you actually have spare cycles to invest for very cool but non critical features.

If you decide to go ahead, I can certainly have a look and help out with testing or debugging if you think that's useful.

**Comment by vincentarelbundock** [comment]
I see this issue again, and now I'm thinking "if it ain't broke". Pulling from original sources is a definite improvement over the previous status quo, but I'm afraid this would cause more breakage.

For instance, if a source sends us only half of the valid codes, that could cause major headaches. And if we don't think and guard against all edge cases.

Overall, I'm not sure it's worth it.
