### ISSUE TITLE
CRAN version out of date, request for update 1.1.0 -> 1.1.1

### ISSUE THREAD

**Issue by democracyobserver** [vincentarelbundock/countrycode#214]
Hello there - great work on this package. 

It looks like there was an issue (#199 ) which was solved with commit f72a4d7 but never made it to CRAN? The package version there is still 1.1.0 while the (closed) issue updated to v. 1.1.1 to fix a bug.

**Comment by vincentarelbundock** [comment]
Thanks @democracyobserver for bringing this to my attention. I tried to push a release, but CRAN is blocking me for issues related to this: 

https://github.com/vincentarelbundock/countrycode/issues/215

Honestly, not sure what to do, and they haven't responded to my questions...

**Comment by democracyobserver** [comment]
Thanks for looking into this @vincentarelbundock. I read #215 and saw what you did. I wish I had more insight into this and could help. Hopefully CRAN will be able to suggest something. The minimum `R` version tradeoff is not ideal.

**Comment by vincentarelbundock** [comment]
@democracyobserver Unsurprisingly, this was due to user error. I found the fix, and the new version is on its way to CRAN. Thanks again for the nudge!

**Comment by democracyobserver** [comment]
Glad it is fixed now. Thanks for all your work on the package!
