### ISSUE TITLE
Travis CI should test against R 4.0.0

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#221]
Some dependencies break on Travis with R 4.0.0 so we are now testing against old release per: https://github.com/vincentarelbundock/countrycode/pull/219

This should be updated to 4.0.0 when breakage is fixed upstream.

**Comment by vincentarelbundock** [comment]
reminder to myself: Nils created a PR with an update travis script. We can refresh that PR check on the Travis site to see if the upstream problems have been cleared up. Once Travis works on that branch, we can merge the PR>

**Comment by NilsEnevoldsen** [comment]
More info: https://travis-ci.community/t/package-build-failure-on-r-devel-some-packages-need-to-be-reinstalled-using-r-4-0-0/8070

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countrycode/commit/d285cc635f96891e1483a60187cb52d81e092e25
