### ISSUE TITLE
Improve package documentation for rare arguments like `custom_dict` and `custom_match`

### ISSUE THREAD

**Issue by graue70** [vincentarelbundock/countrycode#226]
The function documentation for `countrycode()` (as can be seen by running `?countrycode`) is not very clear about the usage of the arguments `custom_dict` and `custom_match`. In addition, the examples don't show how these two arguments can be used at all.
It was not at all clear to me that I would find a better documentation on github. It took quite some time to find it.

Note: These suggestions mostly also apply to the other arguments. Take the two mentioned ones as examples.

Suggestions:

- The examples show only the easiest use of the function. Add examples which actually use the more complicated arguments. I don' think the examples from the github readme are perfect (as they don't make the following points very clear either), but they would still be very helpful for package users.
- Make clear that `custom_dict`, if used, **replaces** the default data. I thought that it **extends** it as an additional data source.
- Make clear what `custom_match` should look like exactly. Particularly, the sentence '_The name of each element will be used as the origin code, and the value of each element will be used as the destination code._' is misleading at worst and confusing at best. _(I tried `custom_match <- c(iso2c = "iso3c")` and wondered where to put the actual data.)_ It should also be mentioned that there are no checks whether `destination` and `custom_match` match at all. There should also be an example making this clear, e. g.:
```
library(countrycode)
country_names <- c('Greece', 'United Kingdom', 'Germany', 'France')
custom_match <- c(Greece = 'EL', `United Kingdom` = 'UK')
countrycode(country_names, 
            origin = 'country.name', 
            destination = 'iso2c', 
            custom_match = custom_match)
countrycode(country_names, 
            origin = 'country.name', 
            destination = 'iso3c', 
            custom_match = custom_match)  # Mixed output. Not checked by the function!
```

**Comment by cjyetman** [comment]
If I understand you correctly, you're suggesting *not* that `destination` and `custom_match` should match, but that the right-hand side values in `custom_match` should match values in the list of individual codes/names contained in the specified destination code?

Or that we should define a list of characteristics for every destination code and check that all of the right-hand side values in `custom_match` fit those characteristics? e.g. when using `destination = 'iso3c'`, all right-hand side values in `custom_match` must be
- a string
- 3 characters long
- all uppercase letters
- only alpha characters
- etc.

1. That's maybe feasible with `iso2c` and `iso3c` destination codes which are fairly restrictive, but probably difficult to impossible with many of the other destination codes.

2. I'm not sure we would want to enforce that all of the time... e.g. a user might want to do something like...

``` r
country_names <- c('Greece', 'United Kingdom', 'Germany', 'France')
custom_match <- c(Greece = NA, `United Kingdom` = 'undefined')

countrycode(country_names, 
            origin = 'country.name', 
            destination = 'iso2c', 
            custom_match = custom_match)
#> [1] NA          "undefined" "DE"        "FR"
```

**Comment by vincentarelbundock** [comment]
So maybe the original impulse to clarify the documentation is the right one?

**Comment by cjyetman** [comment]
on the suggested three points...

1. Sure, I can see how having some examples in the help file that use `custom_dict` and `custom_match` would be helpful.

2. I thought it was pretty obvious that `cust_dict` **replaces** the default dictionary with a custom one, while `cust_match` essentially **extends** the default dictionary with custom individual matches, but I don't see any harm in making that more explicit.

3. This one is very difficult to word. I thought about it for a few minutes, and I can't quickly come up with a way of explaining it that couldn't be misunderstood one way or another and/or is not exceptionally long and wordy. I don't believe the current text is "misleading", but I do believe that it can be misunderstood, and I don't have a better suggestion at the moment (e.g. @graue70's suggestion of mentioning that there are no checks if `destination` and `custom_match` match at all is also confusing / potentially misunderstood / not quite precise or correct)

4. On the suggestion of checking whether the right-hand side values of `custom_match` fit to the same format of values in the dictionary for the defined `destination` code (assuming I understood that suggestion correctly)... that's probably better discussed over in #227.

**Comment by vincentarelbundock** [comment]
Commit https://github.com/vincentarelbundock/countrycode/commit/fea533977b30e5d40e96bc3903b678e889a3a6b6 makes the following changes:

1. Add example of `custom_match` to `?countrycode`

```r
# Using custom_match to supercede default codes
countrycode(c('United States', 'Algeria'), 'country.name', 'iso3c')
countrycode(c('United States', 'Algeria'), 'country.name', 'iso3c', custom_match = c('Algeria' = 'ALG'))
```

2. Add example of `custom_dict` to `?countrycode`

```r
# Using `custom_dict` to convert US States names
cd <- 'https://raw.githubusercontent.com/vincentarelbundock/countrycode/master/data/extra/us_states.csv'
cd <- read.csv(cd)
countrycode(c('AL', 'AK'), 'abbreviation', 'state', custom_dict = cd)
countrycode(c('Alabama', 'North Dakota'), 'state.regex', 'state', custom_dict = cd, origin_regex = TRUE)
```

3. Change the wording of the `custom_dict` parameter description in `?countrycode`:

```
custom_dict: A data frame which supplies a new dictionary to replace
          the built-in country code dictionary. Each column contains a
          different code and must include no duplicates. The data frame
          format should resemble `countrycode::codelist`.  Warning:
          when `custom_dict` is used, no sanity checks are conducted.
```

4. Improved README section called "custom_dict: Custom dictionaries and American states" where it gives a clear example.

Says explicitly:

> Since version 0.19, countrycode accepts user-supplied dictionaries via the custom_dict argument. These dictionaries will override the built-in country code dictionary.

5. Improved README section called "custom_match: Override default values"

My guess is that this should clarify matters considerably. @graue70 @cjyetman do you agree?

**Comment by graue70** [comment]
That looks great and happened very quickly. The only remark I have is that my suggestion to add a note about the missing sanity check was about `custom_match`, not `custom_dict` (though it's also true for it I guess). It should probably be there for both parameters.

I would also like the example I gave in https://github.com/vincentarelbundock/countrycode/issues/226#issue-616986786 to be included to make the missing sanity check even clearer, but maybe that would be overkill. It might even be hurtful because it would show in what way the function can be misused. I'll leave that for you to decide.

**Comment by vincentarelbundock** [comment]
OK, great. Honestly, neither CJ nor I knows exactly who to phrase the sanity check issue. And my sense is that the commit mentioned above with doc improvements solves most of the problem. So I'll close this issue for now. If you have a specific sentence that you'd like added to doc, feel free to open a PR or a new issue with the EXACT wording to be discussed.

Thanks again for your feedback.
