### ISSUE TITLE
Add check for matching `destination` and `custom_match`

### ISSUE THREAD

**Issue by graue70** [vincentarelbundock/countrycode#227]
In this example, the function can be used to produce mixed output. There is no check for whether `destination` and `custom_match` match:
```
library(countrycode)
country_names <- c('Greece', 'United Kingdom', 'Germany', 'France')
custom_match <- c(Greece = 'EL', `United Kingdom` = 'UK')
countrycode(country_names, 
            origin = 'country.name', 
            destination = 'iso3c', 
            custom_match = custom_match)  # Mixed output. Not checked by the function!
```

The question is whether this is good or bad behavior. Leave the current flexibility or add consistency?

**Comment by graue70** [comment]
> [...] I haven't thought about the necessity for [checks] much, but could be convinced that some more transparent reporting would be useful.

(from #226)

Apart from the question whether added checks are good, I don't see how they are possible. Of course 'iso2c' and 'iso3c' can be checked, but 'country.name' cannot. Would it be a good idea to add checks to some destinations but not others? That might be confusing to use.

**Comment by cjyetman** [comment]
My comment here https://github.com/vincentarelbundock/countrycode/issues/226#issuecomment-627788773 is probably more relevant in this issue.

**Comment by vincentarelbundock** [comment]
Commit https://github.com/vincentarelbundock/countrycode/commit/fea533977b30e5d40e96bc3903b678e889a3a6b6 makes the following changes:

1. Add example of `custom_match` to `?countrycode`

```r
# Using custom_match to supercede default codes
countrycode(c('United States', 'Algeria'), 'country.name', 'iso3c')
countrycode(c('United States', 'Algeria'), 'country.name', 'iso3c', custom_match = c('Algeria' = 'ALG'))
```

2. Add example of `custom_dict` to `?countrycode`

```r
# Using `custom_dict` to convert US States names
cd <- 'https://raw.githubusercontent.com/vincentarelbundock/countrycode/master/data/extra/us_states.csv'
cd <- read.csv(cd)
countrycode(c('AL', 'AK'), 'abbreviation', 'state', custom_dict = cd)
countrycode(c('Alabama', 'North Dakota'), 'state.regex', 'state', custom_dict = cd, origin_regex = TRUE)
```

3. Change the wording of the `custom_dict` parameter description in `?countrycode`:

```
custom_dict: A data frame which supplies a new dictionary to replace
          the built-in country code dictionary. Each column contains a
          different code and must include no duplicates. The data frame
          format should resemble `countrycode::codelist`.  Warning:
          when `custom_dict` is used, no sanity checks are conducted.
```

4. Improved README section called "custom_dict: Custom dictionaries and American states" where it gives a clear example.

Says explicitly:

> Since version 0.19, countrycode accepts user-supplied dictionaries via the custom_dict argument. These dictionaries will override the built-in country code dictionary.

5. Improved README section called "custom_match: Override default values"

My guess is that this should clarify matters considerably. @graue70 @cjyetman do you agree?

**Comment by cjyetman** [comment]
looks good to me, but Commit fea5339 is more related to #226 and does not resolve this issue of whether or not and how to implement checking of the values passed to `cust_match`

**Comment by vincentarelbundock** [comment]
yep, sorry posted in the wrong issue.

**Comment by graue70** [comment]
So, there are three comments which don't belong to the issue and the only comment that does belong here, isn't here. That's confusing. ;) Is there a way to clean up this ticket's comments and copy the relevant comment over to this one?

**Comment by vincentarelbundock** [comment]
After reading this more carefully, I don't think that `countrycode` should be doing much sanity check (if any) here. We'd need to encode and *maintain* a whole set of relevant features to check against for each code, or we'd need to implement and *maintain* some semi-smart feature guessing.

I also think that allowing users to input anything as the `custom_match` output is a nice, powerful, feature.

Finally, the text in the document seems very clear to me (emphasis added):

> custom_match: A named vector which supplies custom origin and
          destination matches that will **supercede any matching default
          result**. The name of each element will be used as the origin
          code, and the value of each element will be used as the
          destination code.
