### ISSUE TITLE
argument to only return the top match from guess_field

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#246]
I think it could be useful to have an argument in the `guess_field` function that, when set to `TRUE`, would only return the top match, and only the code name/value. This could enable something like...
```
countrycode(sourcevar = df$mysterious_country_code, 
            origin = guess_field(sourcevar, only_top = TRUE),
            destination = 'country.name')
```
That could then even be added as the default `origin` value for `countrycode`, making `countrycode` by default work much like `countryname`, in that it would automatically guess the most appropriate origin code, so this would work under most conditions...
```
countrycode(sourcevar = df$mysterious_country_code, 
            destination = 'country.name')
```

**Comment by vincentarelbundock** [comment]
Not convinced. 

```r
countrycode(sourcevar = df$mysterious_country_code, 
            origin = guess_field(sourcevar)$code[1],
            destination = 'country.name')
```

Also, that seems like terrible coding practice, and I'm not sure we want to encourage such dark magic.

**Comment by vincentarelbundock** [comment]
Not convinced. This is shorter than your code.

```r
countrycode(sourcevar = df$mysterious_country_code, 
            origin = guess_field(sourcevar)$code[1],
            destination = 'country.name')
```

Also, that seems like terrible coding practice, and I'm not sure we want to encourage such dark magic.

**Comment by cjyetman** [comment]
fair enough...

I was thinking along the lines of how, for instance, `readr::read_csv` works. If you don't specify what the column types are, it guesses for you, and it's really good at it. Though it always prints a message with a list of what guesses it made.

I suspect that `guess_field` will be *very* good at guessing the most appropriate code. A less "dark magic" approach could be to check the user's input for `origin` against what `guess_field` thinks it should be, and potentially print a warning like "Hey, you specified iso2c as the origin code, but it's very likely that it should be eurostat because your sourcevar includes 'UK' and 'EL'", which probably could have avoided a number of the support questions we've received here over the past few years about why iso2c is not matching a few countries, etc.

As a user, I think I'd be a bit more annoyed by that though... explicitly setting an option and then having the function tell me I'm probably wrong. Which is why, for better or worse, I prefer the strategy of guessing for the user by default, unless they explicitly specify something, in which case just trust they chose that for a reason.

But anyway, it was just a thought... I'm not advocating strongly in any direction (or no direction).

**Comment by vincentarelbundock** [comment]
Cool. I see how this could be useful, but at the same time it seems like a good idea to require some agency on the part of the user.

I suggest we sit on this for a while and revisit if/when we become convinced that this is a good idea.
