### ISSUE TITLE
build a pkgdown website

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#249]

**Comment by vincentarelbundock** [comment]
@cjyetman I didn't do any customization so this is just the vanilla pkgdown website, but it looks pretty good to me already:

https://vincentarelbundock.github.io/countrycode/

**Comment by cjyetman** [comment]
looks cool, and hopefully it's easy to manage/update

quick comments:
- I think it would be good to have a link to the GitHub page somewhere on the main page
- two backticks at the end of the install command? "install.packages("countrycode")``"
- a CRAN badge might be nice - https://www.r-pkg.org/services
- and/or an R CMD check badge - https://usethis.r-lib.org/reference/github_actions.html

different topic...
- we could add a bug/issues URL to the DESCRIPTION file with `BugReports: https://github.com/vincentarelbundock/countrycode/issues`

**Comment by vincentarelbundock** [comment]
Good suggestions! All done!

I'm not super familiar witth R CMD check badge, and I think it's possible to add more testting platform in the setup file, but no time to investigate now.

`pkgdown` is dead easy. You just run `pkgdown::deploy_to_branch` and it pulls everything automatically from the README and updates the site.
