### ISSUE TITLE
test that a custom dictionary with unique column names works

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#271]
> 2. I think this might conflict with custom dictionaries where we won't know the names of the columns, and hence the possible values for `origin` or `destination`.

_Originally posted by @cjyetman in https://github.com/vincentarelbundock/countrycode/issues/270#issuecomment-805596311_

Based on the above comment, it would probably be a good idea to have a test that tests if a custom dictionary with unique column names works.

**Comment by vincentarelbundock** [comment]
Could you clarify a bit how this differs from:

https://github.com/vincentarelbundock/countrycode/blob/main/tests/testthat/test-custom-dictionary.R

**Comment by cjyetman** [comment]
these indirectly cover it, so closing
https://github.com/vincentarelbundock/countrycode/blob/e85e44f4505d55d8b09c888f78b5eaf47df96fbc/tests/testthat/test-custom-dictionary.R#L22-L24
