### ISSUE TITLE
countrycode_factory is unrecognised

### ISSUE THREAD

**Issue by tanushree-rao** [vincentarelbundock/countrycode#273]
![image](https://user-images.githubusercontent.com/35216964/113848472-cc19d400-9798-11eb-9ca0-45d0b01862a7.png)

This function is included in the readme on this repo but seems not to work in R. Unsure if it requires defining the function first (not found in readme/docs in this repo, may have missed it?).

**Comment by cjyetman** [comment]
I don't think `countrywide_factory()` has made it into a CRAN released version yet. You'll have to install the dev version of `countrycode` to try it out, which you can do with something like: `devtools::install_github("vincentarelbundock/countrycode")`
