### ISSUE TITLE
Taiwan numeric code is missing where it should be 158?

### ISSUE THREAD

**Issue by iago-pssjd** [vincentarelbundock/countrycode#283]
Hi!,

Thanks for the great package.

`codelist$un[codelist$country.name.en == "Taiwan"]` is missing, but it seems to have numeric code 158 (https://www.iso.org/obp/ui/#iso:code:3166:TW)

**Comment by cjyetman** [comment]
UN's M49 does not include Taiwan, but IS0-3166 does.

https://unstats.un.org/unsd/methodology/m49/overview/
```r
countrycode("Taiwan", "country.name", "un")
# [1] NA
```

https://www.iso.org/obp/ui/#iso:code:3166:TW
```r
countrycode("Taiwan", "country.name", "iso3n")
# [1] 158
```

**Comment by iago-pssjd** [comment]
Thanks! I see.
