### ISSUE TITLE
'korea, dem. rep.' should be north korea, not south

### ISSUE THREAD

**Issue by iamgyang** [vincentarelbundock/countrycode#286]
countrycode("korea, dem. rep.", 'country.name', 'iso3c') gives "KOR", not "PRK".

**Comment by NilsEnevoldsen** [comment]
Hm. Is this test passing? https://github.com/vincentarelbundock/countrycode/blob/bffe4c78e48e3cccf8e161d3d622228672e9db28/tests/testthat/data-known-name-variations.R#L96

**Comment by iamgyang** [comment]
Sorry--I had to delete and reinstall the package. Fixed now. My bad!

**Comment by NilsEnevoldsen** [comment]
Ah, fixed in https://github.com/vincentarelbundock/countrycode/commit/0e618a5c0aec3a8aabedfac0394e339d5b37cd48.
