### ISSUE TITLE
Mircronesia missing in iso2c

### ISSUE THREAD

**Issue by herrmol** [vincentarelbundock/countrycode#289]
It seems that the iso2c for Micronesia is missing though the iso2c code for Micronesia is "FM".

**Comment by vincentarelbundock** [comment]
I think there is a distinction between:

  - Micronesia is the region:
    <https://en.m.wikipedia.org/wiki/Micronesia>
  - Federated States is a country:
    <https://en.m.wikipedia.org/wiki/Federated_States_of_Micronesia>



``` r
library(countrycode)

countrycode("Micronesia", "country.name", "iso2c")
```

    ## Warning in countrycode_convert(sourcevar = sourcevar, origin = origin, destination = dest, : Some values were not matched unambiguously: Micronesia

    ## [1] NA

``` r
countrycode("Federated States of Micronesia", "country.name", "iso2c")
```

    ## [1] "FM"

You can use the `custom_match` argument to fill in the missing values if you want to assign "Micronesia" to an iso2c code.
