### ISSUE TITLE
Convert between currency name and currency codes

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#293]
A user on [StackOverflow recently asked](https://stackoverflow.com/questions/67373611/how-to-convert-iso-4217-code-to-currency-name-in-r) how to convert a currency code to a currency name for nicer looking labels on a plot. In the specific example data they gave, the country name was available, making `countrycode(country, "country.name", "currency")` an easy solution, however, another commenter still strongly believed that `countrycode()` should do the currency code and currency name conversion "out-of-the-box".

This is easy enough to do using the `custom_dict` argument and some modification of `countrycode::codelist`, and the maintainers here know all to well why `currency` and `iso4217c` are "destination-only" codes, but since the data to achieve this is already included in the package, I wonder if there's an appropriate way to do this easily.

The least controversial solution would be to add a custom currency dictionary to our custom dictionaries based on that data we already have. Alternatively, we could consider adding some magic inside `countrycode()` to switch things up when a destination-only code is used for the origin code and a matching one-to-one destination code is requested.

``` r
library(countrycode)

currency_codes <- c("AFN", "EUR", "USD")
currency_codes_n <- c(971, 978, 840)
currencies <- c("Afghani", "Euro", "US Dollar")

custom_dict <- countrycode::codelist
custom_dict <- custom_dict[!duplicated(custom_dict$currency), ]


countrycode(currency_codes, "iso4217c", "iso4217n", custom_dict = custom_dict)
#> [1] 971 978 840
countrycode(currency_codes, "iso4217c", "currency", custom_dict = custom_dict)
#> [1] "Afghani"   "Euro"      "US Dollar"

countrycode(currency_codes_n, "iso4217n", "iso4217c", custom_dict = custom_dict)
#> [1] "AFN" "EUR" "USD"
countrycode(currency_codes_n, "iso4217n", "currency", custom_dict = custom_dict)
#> [1] "Afghani"   "Euro"      "US Dollar"

countrycode(currencies, "currency", "iso4217c", custom_dict = custom_dict)
#> [1] "AFN" "EUR" "USD"
countrycode(currencies, "currency", "iso4217n", custom_dict = custom_dict)
#> [1] 971 978 840
```

**Comment by cjyetman** [comment]
possibly related #265

**Comment by cjyetman** [comment]
> One "magic" option would be to include an attribute to the dictionary with a vector of destination-only codes.

Yeah, I was thinking of something like maintaining a named vector matching origin-code -> most-appropriate-dictionary.

pseudo-code...
```r
countrycode <- function(sourcevar, origin, destination) {
  origin_to_dict <- c("country.name" = codelist, "iso3c" = "codelist", "currency" = currency_dict)
  dictionary <- origin_to_dict[origin == names(origin_to_dict)]
  ...
}
```

**Comment by vincentarelbundock** [comment]
After reviewing this, my sense is that this is a rehash of the many-to-one mapping issue: https://github.com/vincentarelbundock/countrycode/issues/186

Users can already get a custom dictionary by calling:

```r
codelist[, c("country.name", "iso4217c")]
```

I think we can close this and revisit in the future if someone decides to invest the considerable efforts that would be needed to implement a truly general many-to-one solution.
