### ISSUE TITLE
Is the UN-official Spanish name for Trinidad and Tobago really Trinidad y Tabago?

### ISSUE THREAD

**Issue by NilsEnevoldsen** [vincentarelbundock/countrycode#299]
Not an issue, just a request for feedback.

Is the UN-official Spanish name for Trinidad and Tobago _really_ Trinidad y Tabago? It's given as such [here](https://unstats.un.org/unsd/geoinfo/ungegn/docs/11th-uncsgn-docs/E_Conf.105_13_CRP.13_15_UNGEGN%20WG%20Country%20Names%20Document.pdf), and it's in my latest pull request under the assumption that it's genuine. It does appear to be a real variant, but a rare one. For example, it's not mentioned at https://es.wikipedia.org/wiki/Trinidad_y_Tobago. However, it is about twice as frequent as Trinidad y Tobago on un.org.

Out of curiousity, if Trinidad y Tabago is correct, does anyone know _why_ it was chosen?

**Comment by NilsEnevoldsen** [comment]
This person shares my confusion: https://es.wikipedia.org/wiki/Discusión:Trinidad_y_Tobago#Tobago_o_Tabago

**Comment by NilsEnevoldsen** [comment]
These appear to be the most official current documents.

[UNGEGN List of Country Names](https://unstats.un.org/unsd/geoinfo/ungegn/docs/11th-uncsgn-docs/E_Conf.105_13_CRP.13_15_UNGEGN%20WG%20Country%20Names%20Document.pdf) (E/CONF.105/13/CRP.13)
[UNGEGN List of Country Names](https://unstats.un.org/unsd/ungegn/sessions/2nd_session_2021/documents/GEGN.2_2021_CRP130_4c_WG_Country_Names_rev2.pdf) (GEGN.2/2021/CRP.130/Rev.1)

I have emailed the chair of the working group to ask if it is an error.

**Comment by vincentarelbundock** [comment]
That’s interesting. For what it’s worth, it also seems to be the Unicode CLDR name:

``` r
library(countrycode)

countrycode("Trinidad and Tobago", "country.name", "cldr.short.es")
#> [1] "Trinidad y Tobago"
```

**Comment by NilsEnevoldsen** [comment]
I actually just received a reply.

> Thank you for bringing my attention to this question, which really looks 
like a mistake.
> 
> I will check this and make an appropriate decision if we find an 
official basis to do so.

**Comment by vincentarelbundock** [comment]
ha! that's kind of cool

**Comment by NilsEnevoldsen** [comment]
I'll call this closed with 2168ec9c7d8f241496155268d08587f8de3bc8eb. If we learn anything surprising we can reopen.

**Comment by NilsEnevoldsen** [comment]
I have learned something surprising, and am reopening.

Correspondence with names redacted:

> After a long inquiry, we've finally found the expert who knew the answer to your question: my French colleague ______ ______.
>
> In short, the name used in Spain is "Trinidad y Tobago", but the Spanish name for UN use, officially stated by the country itself (whose official language is English), is really "Trinidad y Tabago".
>
> Indeed, under British rule, the name of the island was Tobago or Tabago, and this "name, given by Christopher Columbus, came from the Haitian "tambaku" ("pipe") because of the habit that the inhabitants had of inhaling by mouth the products resulting from the combustion of tobacco leaves (Cherpillod, etymological dictionary of geographical names, 1991)."

My reply:

> Wow! This is indeed surprising, given how rarely that form is used. Thanks to ______ ______ for finding this.
>
> If I might make one further inquiry: in what manner and when was the Spanish name “officially stated by the country itself”. Is this official statement in a public document? In a private document? In meeting notes?

I was answered:

> In principle, the names are declared to the United Nations Protocol and Liaison Service by the Permanent Mission of the requesting country, as in the attached document. [The attachment was for Czechia.]
>
> For the case that interests you, it seems to me that you should ask the United Nations archives.
>
> For my part, I had taken notes in a small committee meeting: my boss, ______ ______, and I were in contact with Mr. Nigel Kasser and his linguistic secretary (in charge of the list of country names) who had given the information... the documents were not yet digitized.

**Comment by vincentarelbundock** [comment]
This is fascinating. It's amazing what info we can get by "just asking." Good stuff, thanks for sharing!

**Comment by vincentarelbundock** [comment]
Was reviewing this, and I get a sense that there is no action to take here. Correct? Can close?

**Comment by NilsEnevoldsen** [comment]
Not at a computer, but I think 2168ec9c7d8f241496155268d08587f8de3bc8eb hasn't been reverted yet. I was hoping to get confirmation from T&T before I did that, but I've received no response. Thus we should assume the UN is correct and revert to "Tabago".

**Comment by vincentarelbundock** [comment]
Got it, thanks! I commented out the lines where we changed it manually, but have been unable to re-run the `get_un_names.R` script because of this issue: https://github.com/vincentarelbundock/countrycode/issues/312

**Comment by vincentarelbundock** [comment]
Reverted and tested here: a5d98a76b74688a5390698a8743131c1b96b13d

**Comment by dieghernan** [comment]
My two cents on this:

<https://www.rae.es/dpd/Trinidad%20y%20Tobago> [Spanish]
Auto-translate:

> Trinidad and Tobago
> 
> 1. A South American country, made up of these two islands and several islets located off the northeastern coast of Venezuela: "The Costa Rican national team expects an easy victory over Trinidad and Tobago" (Tiempo co 1.9.1996). This name is preferable to the also used Trinidad and Tabago, since the traditional form Tabago for the name of the second of the islands was displaced at the end of the 19th century by the English form Tobago, now fully established in Spanish: "The butcher Achilles, a black man from the island of Tobago" (Carpentier Siglo cu 1962). The demonym is Trinitense: "The Trinitenses defeated Panama, 1 to 0, in Port of Spain" (Nación cr 16.11.2000).
