### ISSUE TITLE
Not matching for Turkey's new official name

### ISSUE THREAD

**Issue by hgoers** [vincentarelbundock/countrycode#307]
Hello all, 

Thank you so much for `countrycode`. I use it almost every day to support my work and research. 

I noticed a small issue resulting from the recent official name change for Turkey. The current regex does not pick up this new name: Türkiye.

**Reprex:** 
```
countrycode::countrycode("Türkiye", "country.name", "country.name")
```

**Warning thrown:**
```
Warning message:
In countrycode_convert(sourcevar = sourcevar, origin = origin, destination = dest,  :
  Some values were not matched unambiguously: Türkiye
```

I was able to convert it with the rather crude `turkey|türkiye|turkiye`.

Thanks!

**Comment by vincentarelbundock** [comment]
The default regexes are designed to pick up English names. You could try then `countryname()` which tries to do more clever stuff

**Comment by NilsEnevoldsen** [comment]
I agree with the issue. Türkiye is going to be seen in English more often now.

**Comment by hgoers** [comment]
My understanding is that Türkiye is to be used in English and French (I am not sure about other languages). It would be really useful if `countrycode::countrycode` could either convert Turkey to Türkiye (and Turquie to Türkiye) to reflect this new official name, or if the `country.name.X.regex` picked up Türkiye and converted it to Turkey (Turquie).

**Comment by hgoers** [comment]
Thanks so much for a fantastic package!
