### ISSUE TITLE
Turkey -> Turkiye

### ISSUE THREAD

**Issue by BPJandree** [vincentarelbundock/countrycode#310]
Dear Vincent,

I'm less familiar with the inner workings of this package but assume it will similarly be affected by the Turkey -> Turkiye name change.

I know some applications use countrycode to make calls via WDI (or take WDI data and pass it through countrycode) which will either way likely break.

My sense it's a simple update of the ```countryname_dict.rda``` but I'm not sure how different languages have taken up the name change and what formally would be the best approach. There could also be backward compatibility issues associated with simply swapping the name.

Perhaps for user experience adding an exception somewhere in the code so that both 

```countrycode("Turkey", origin="country.name", destination = "iso3c")```

and

```countrycode("Turkiye", origin="country.name", destination = "iso3c")```

will work. Right now the second does not:

```vim
> countrycode("Turkey", origin="country.name", destination = "iso3c")
[1] "TUR"
> countrycode("Turkiye", origin="country.name", destination = "iso3c")
[1] NA
Warning message:
In countrycode_convert(sourcevar = sourcevar, origin = origin, destination = dest,  :
  Some values were not matched unambiguously: Turkiye
```vim

Best,
Bo

**Comment by vincentarelbundock** [comment]
Thanks Bo,

This has already been fixed in the development version which can install from Github. The improved regular expression will be part of the next CRAN release, in the next weeks.

**Comment by BPJandree** [comment]
Great! I'll close then, Best,
