### ISSUE TITLE
Distribute custom dictionaries with the package?

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#315]
A lot of packages distribute data.

Would it make sense for us to distribute a few small custom dictionaries to make people's life easier. For example, it would be nice to distribute the `usstates` dictionary so that users could do:

```r
library(countrycode)
countrycode("Alabama", "state", "stateabb", custom_dict = usstates)
```

The main downside is download size.

What do you think?

**Comment by cjyetman** [comment]
I back that. The compressed `codelist.rda` file is only 242 KB with 288 rows × 621 columns, and presumably most of these custom dictionaries would be much, much smaller.

**Comment by vincentarelbundock** [comment]
The upcoming CRAN release has a new `get_dictionary()` function. See: https://vincentarelbundock.github.io/countrycode/#custom-dictionaries-and-cross-walks-get_dictionary-and-custom_dict
