### ISSUE TITLE
Handling Türkiye

### ISSUE THREAD

**Issue by JohnsonBrent** [vincentarelbundock/countrycode#321]
Might want to update the English dictionaries/codelist to handle "Türkiye".  Not everyone's adopted the name change, but the UN has.  And it's used in recent Eurostat publications. 

Fantastic package, btw!

**Comment by cjyetman** [comment]
see #310 and #308

latest dev version has a fix for this already, but it has not yet been released on CRAN
```r
devtools::install_github("vincentarelbundock/countrycode")
library(countrycode)
packageVersion("countrycode")
#> [1] ‘1.4.1’
countrycode("Turkey", origin="country.name", destination = "iso3c")
#> [1] "TUR"
countrycode("Türkiye", origin="country.name", destination = "iso3c")
#> [1] "TUR"
```
