### ISSUE TITLE
UN re-licensing

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#322]
@cjyetman @NilsEnevoldsen 

I was contacted by someone who works at the United Nations' Center for Humanitarian Data. They would like to use some of our regexes in MIT-licensed software.

Is that OK with you? They would add a note in their copyright file to the effect of:

> Regular expressions from countrycode (https://github.com/vincentarelbundock/countrycode) incorporated and relicensed under The MIT License (MIT) with the kind permission of Vincent Arel-Bundock, Nils Enevoldsen, and CJ Yetman.

**Comment by NilsEnevoldsen** [comment]
Okay with me.

**Comment by cjyetman** [comment]
Fine by me 😁

**Comment by vincentarelbundock** [comment]
Thanks both!
