### ISSUE TITLE
Turkey country name and iso3c

### ISSUE THREAD

**Issue by gclawson1** [vincentarelbundock/countrycode#337]
Turkey has [changed its official name](https://www.npr.org/2022/06/03/1102841197/turkey-changes-its-official-name-to-turkiye) to "Türkiye", and in many of the FAOSTAT datasets that I access, it now shows up as Türkiye. I keep having to manually assign the iso3c for this country because `countrycode(df$countryname, origin="country.name", destination = "iso3c")` doesn't recognize "Türkiye". Are there plans to add this in as a synonym for Turkey?

**Comment by vincentarelbundock** [comment]
Can you make sure you are running the latest version of `countrycode`? It works on my computer.

**Comment by gclawson1** [comment]
Ah apologies, it was an encoding error on my part. Thanks!
