### ISSUE TITLE
Republic of Kosovo (and derivations: Kosovo) returns NA for iso codes. Implement to return XK, XKK

### ISSUE THREAD

**Issue by morrisseyj** [vincentarelbundock/countrycode#355]
Republic of Kosovo (and derivations e.g. Kosovo) returns NA when `destination` is an iso code.

`countrycode("Republic of Kosovo", "country.name", "iso3c") `

and 

`countrycode("Republic of Kosovo", "country.name", "iso2c")`

Both return:
```
[1] NA
Warning message:
Some values were not matched unambiguously: Republic of Kosovo
```

I appreciate that Kosovo only has partial diplomatic recognition, but its included as an IDA country and the World Bank has status in your package. 

Could you implement to return XK or XKK?

**Comment by cjyetman** [comment]
Kosovo does not have an official ISO code (see https://www.iso.org/obp/ui/#search/code/).

I suggest using the `custom_match` argument...
``` r
countrycode("Republic of Kosovo", "country.name", "iso3c", custom_match = c("Republic of Kosovo" = "XKK"))
#> [1] "XKK"

countrycode("Republic of Kosovo", "country.name", "iso2c", custom_match = c("Republic of Kosovo" = "XK"))
#> [1] "XK"
```

**Comment by vincentarelbundock** [comment]
I don't remember the details of the arguments, but this has been discussed several times. If you want to file a feature request, please read the past closed issue and formulate counter-arguments to what was discussed there. For example:

https://github.com/vincentarelbundock/countrycode/issues/305
https://github.com/vincentarelbundock/countrycode/issues/306
https://github.com/vincentarelbundock/countrycode/issues/61

**Comment by NilsEnevoldsen** [comment]
Kosovo is not listed at https://www.iso.org/obp/ui/#search/code/, so we won't include an ISO code for it.

If you want to link to a World Bank dataset, you can use the `wb`, `wb_api2c`, or `wb_api3c` destination codes.

**Comment by vincentarelbundock** [comment]
Hahah, I think we all answered at the exact same time. This wasn't meant to be a pile on ;-)

**Comment by morrisseyj** [comment]
Apologies, i missed all these closed issues. Thanks for the excellent package. I use it constantly.
