### ISSUE TITLE
New release on CRAN?

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/countrycode#356]
Hi Vincent, there are a couple of improvements and speedups in the development version, do you have an idea of when you'd like to submit it to CRAN? No pressure from my side, I'd just prefer using the CRAN version than the dev one.

Btw the last two items in NEWS don't appear on the website, it seems there's no automated workflow for altdoc on this repo.

**Comment by vincentarelbundock** [comment]
thanks for the nudge. website fixed and package submitted to cran

**Comment by etiennebacher** [comment]
Cool, thanks. Also the badge for download counts is wrong since `altdoc` adds the ".png" extension (I thought we had fixed that in `altdoc`)
