### ISSUE TITLE
Odd behavior when using `custom_dict` with `codelist`

### ISSUE THREAD

**Issue by mcooper** [vincentarelbundock/countrycode#358]
I would expect both of these to give the same result, but they dont:

```
countrycode("Myanmar", "country.name", "iso3c")

countrycode("Myanmar", "country.name", "iso3c", custom_dict = countrycode::codelist)
```

I am trying to make a tweak to codelist for one specific country-code (I want to assign Kosovo an ISO-3 code), and I would like to make `countrycode()` otherwise behave the same.  I tried doing that by editing `codelist`, but using `codelist` as the `custom_dict` seems to have other effects.

**Comment by cjyetman** [comment]
I would suggest using the `custom_match` argument...

``` r
library(countrycode)
countries <- c("Myanmar", "Kosovo", "Republic of Kosovo")
countrycode(countries, "country.name", "iso3c", custom_match = c(Kosovo = "XKK", `Republic of Kosovo` = "XKK"))
#> [1] "MMR" "XKK" "XKK"
```
