### ISSUE TITLE
Common name matched more than once

### ISSUE THREAD

**Issue by jameswtc** [vincentarelbundock/countrycode#39]
Hi,

When attempting to match the following name, there are matches more than once for which there should be obvious the second match is "more accurate" given the country names in full:

1: In countrycode(country, "country.name", "iso2c", warn = TRUE) :
  Some strings were matched more than once: Dem. Rep. of the Congo,CG,CD

2: In countrycode(country, "country.name", "iso2c", warn = TRUE) :
  Some strings were matched more than once: Hong Kong, China,CN,HK

3: In countrycode(country, "country.name", "iso2c", warn = TRUE) :
  Some strings were matched more than once: Macao, China,CN,MO

4: In countrycode(country, "country.name", "iso2c", warn = TRUE) :
  Some strings were matched more than once: South Sudan,SS,SD

Nice work, by the way.

**Comment by ClaytonJY** [comment]
I can verify I was having the same Sudan/South Sudan issue, and installing 0.18 from github and restarting R fixed the issue; the Sudan regex no longer matches both "Sudan" and "South Sudan".

**Comment by vincentarelbundock** [comment]
fixed in current github version
