### ISSUE TITLE
[Request] Short country names (for legibility, graph labels)

### ISSUE THREAD

**Issue by LaDilettante** [vincentarelbundock/countrycode#40]
It would be helpful to have short country names as an option. For example:

- "Bolivia, Plurinational State Of" = "Bolivia"
- "Korea, Democratic People'S Republic Of" = "Korea, DPR"

Please let me know if this option can be implemented soon, or whether you're interested in me contributing this option.

**Comment by NilsEnevoldsen** [comment]
The names are, in fact, the ISO 3166 "short names". Perhaps the CIA [*World Factbook*](https://www.cia.gov/library/publications/the-world-factbook/fields/2142.html) "conventional short form" could be an authoritative source for shorter names. I'm unsure whether it would be better to fill in the missing conventional short forms with the ISO short names, or leave hole-filling up to the end user.

**Comment by LaDilettante** [comment]
An important use case for "conventional short form" is for labeling countries on graph. For example, [Pippa Norris's shared data at Harvard](http://www.hks.harvard.edu/fs/pnorris/Data/Data.htm) always have a column for this.

In my opinion, this use case is common enough to warrant an option.

**Comment by NilsEnevoldsen** [comment]
Hm. I went down to grill her about her data sources, but there's a note on her door saying she split to Australia for a spell. You could email her and ask what her source is. Whatever it is, I'm not sure I like it. For example "Libya Arab Jamahiriy" is dubious in three different ways. (Two typos, and probably should be "Libya" in the short-short form anyway.)

**Comment by LaDilettante** [comment]
Is there plan to implement this feature? As I mentioned, the use case for short, conventional country name is for graph labeling a` la [Pippa Norris dataset](http://www.hks.harvard.edu/fs/pnorris/Data/Data.htm)

**Comment by NilsEnevoldsen** [comment]
No, there is no current plan to implement this feature.

I suggest that we should welcome a pull request that adds the CIA World Factbook "conventional short form", with missing conventional short forms filled either by ISO short names or our own judgment. Most of the controversial decisions (like Taiwan) will be for entities large enough to be covered by the CIA, so we don't have to stick our neck out for them.

**Comment by vincentarelbundock** [comment]
I'm thinking about a way to facilitate the use of custom mappings, with dictionaries hosted in this Github repo. This could be a nice use-case. Pointing to it in the appropriate thread.

If you can put together a data.frame with two rows (iso3c and short names), I'd be a taker.

https://github.com/vincentarelbundock/countrycode/issues/67
