### ISSUE TITLE
Taiwan is not supposed to be called "Taiwan, Province Of China"

### ISSUE THREAD

**Issue by LaDilettante** [vincentarelbundock/countrycode#44]
On the same issue of Taiwan's name as this [open issue](https://github.com/vincentarelbundock/countrycode/issues/43), but from another angle: Taiwan is not a province of China (as a indignant Taiwanese colleague of mine point out) :)

**Comment by rfilmyer** [comment]
FYI Taiwan, Province of China is Taiwan's [ISO_3166-1 English short name](http://en.wikipedia.org/wiki/ISO_3166-1). This is [not a unique issue](http://meta.stackexchange.com/questions/170143/taiwan-is-not-a-province-of-china) to this program, by [any means](https://www.change.org/p/iso-change-the-present-taiwan-province-of-china-to-taiwan-4), and it's a question that was bound to come up.

**Comment by LaDilettante** [comment]
Interesting. I knew the country names in `countrycode` comes from some ISO standard, but did not know that people have talked about this for a long time.

Given that `countrycode` is used quite a bit by political scientists (I presume), has no one brought this up before?

I think it would be great if you shorten Taiwan's name to just "Taiwan" (likewise with Bolivia, etc.), but you decide, of course.

**Comment by vincentarelbundock** [comment]
Going with @NilsEnevoldsen suggestion. Thanks all for your input.
