### ISSUE TITLE
TW is not matched to a region of the world

### ISSUE THREAD

**Issue by dmgerman** [vincentarelbundock/countrycode#47]
TW is not matched to a region of the world (Eastern Asia) nor continent (Asia)

**Comment by NilsEnevoldsen** [comment]
The World Bank doesn't recognize Taiwan, so it doesn't assign Taiwan to a continent. I don't know what to do about this. On the one hand, it would make sense to classify Taiwan as the same region as China. On the other hand, that would mean the region column no longer represents WB region classifications. Should we assign common-sense regions on an ad-hoc basis?

**Comment by vincentarelbundock** [comment]
made an executive decision to give taiwan the same region as china. it's in the CSV file and will be updated the next time I run prep.R and make a release

**Comment by rempsyc** [comment]
It seems Taiwan still has no associated region when using the `genc2c` standard. Should it also be Asia and Eastern Asia?

``` r
library(countrycode)
packageVersion("countrycode")
#> [1] '1.6.0'

"China" |>
  countrycode("country.name", "genc2c") |>
  countrycode("genc2c", "un.region.name")
#> [1] "Asia"

"China" |>
  countrycode("country.name", "genc2c") |>
  countrycode("genc2c", "un.regionsub.name")
#> [1] "Eastern Asia"

"Taiwan" |>
  countrycode("country.name", "genc2c") |>
  countrycode("genc2c", "un.region.name")
#> Warning: Some values were not matched unambiguously: TW
#> [1] NA

"Taiwan" |>
  countrycode("country.name", "genc2c") |>
  countrycode("genc2c", "un.regionsub.name")
#> Warning: Some values were not matched unambiguously: TW
#> [1] NA
```

<sup>Created on 2024-10-17 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by NilsEnevoldsen** [comment]
`genc2c` is a red herring; the root problem is that the UN doesn't recognize Taiwan.

```r
> countrycode("Taiwan", "country.name", "un.region.name")
[1] NA
Warning message:
Some values were not matched unambiguously: Taiwan
```

If you need to use United Nations regions, you can assign Taiwan manually. 

As an alternative, you can use one of the following World Bank regional definitions.

```r
> countrycode("Taiwan", "country.name", "continent")
[1] "Asia"

> countrycode("Taiwan", "country.name", "region")
[1] "East Asia & Pacific"

> countrycode("Taiwan", "country.name", "region23")
[1] "Eastern Asia"
```

**Comment by rempsyc** [comment]
Thanks. Yes it's for a package where I'm trying to streamline the workflow using `genc2c`, so I probably need to carve an exception whereas if `genc2c == TW`, then assign country myself, then only assign country with countrycode if it doesn't already exist.
