### ISSUE TITLE
Could there be a wiki page explaining the difference between the different country code system?

### ISSUE THREAD

**Issue by LaDilettante** [vincentarelbundock/countrycode#48]
I have been trying to Google the difference between the various systems -- however the information is very scattered and unsystematic. At the moment, that leaves my choice of, say, `iso2c` vs `iso3c` largely arbitrary.

I suspect that in the process of writing this package, you have gained a working understanding of the systems. A wiki page would greatly help the package user choosing the appropriate system.

**Comment by vincentarelbundock** [comment]
Yeah, honestly, my big takeaway from working on this is: "what the hell". Not sure this would make a great wiki :)

Would be happy to add a wiki if you have contributions, though. Thanks!
