### ISSUE TITLE
[Request] Google Maps API-compatible country names

### ISSUE THREAD

**Issue by ulfelder** [vincentarelbundock/countrycode#49]
This package is terrific; thanks so much for creating and maintaining it.

Any chance you could add country names that are fully compatible with Google Maps API as an option for `origin` and `destination`? Maybe call it "google.names"?

This comes up because I am trying to use ggmap's `get_map(source = "google", location = [countryname])` to map and then plot points in countries called from a data frame that has used `countrycode` to create those names from iso3c codes. Most of the names work fine, but I've found a number of exceptions that return wacky results (e.g., a map of Tasmania when `location = "Tanzania, United Republic of"`. I'm probably not the only person doing this, and I think this request overlaps with a previous one for an option for short-form names.

Also, I don't think it would require many variations on the existing name list. I went through and tried mapping ones that seemed like they could be problematic, and these were the only ones that seemed to require attention (with working alternatives after the -->):

Tanzania, United Republic of --> Tanzania
Bolivia, Plurinational State of --> Bolivia
Congo, the Democratic Republic of the --> Democratic Republic of the Congo; DRC
Korea, Democratic People's Republic of --> North Korea
Korea, Republic of --> South Korea
Macedonia, the former Yugoslav Republic of --> Macedonia
Syrian Arab Republic --> Syria
Venezuela, Bolivarian Republic of --> Venezuela

Oh, and one last note: I tried using the iso3c codes as the location in the call to `get_map()`, but that doesn't work either.

**Comment by vincentarelbundock** [comment]
Hey Jay @ulfelder thanks for the issue and sorry for the delay. Big fan of your work! (I just ordered the polity joy division shirt and can't wait to wear it).

Huh, yeah, I guess that would be fine. I'm running through issues now, and I wouldn't mind adding this, but I have basically zero bandwidth to do any research on this. If want to add a column to the CSV file I'll merge, but otherwise I'm afraid I'll have to punt. Sorry!
