### ISSUE TITLE
Add functionality of the stata package ``kountry``

### ISSUE THREAD

**Issue by kendonB** [vincentarelbundock/countrycode#50]
This package, for example, allows the user to easily add spellings of each country's long name. The package could also provide wrapper functions to extract continent, region, and convert long names to country codes.

**Comment by briatte** [comment]
You might want to check PR #64 for some functionality that might serve your needs.

It wouldn't take much to have `countrycode` behave a bit like country: if the country codes dataset were an argument of the `countrycode` function, then it becomes trivial to export the packaged dataset, edit it (possibly by adding new columns), and then use that as the source. I'll make a PR to suggest that functionality when I am done with another idea.

**Comment by vincentarelbundock** [comment]
The general solution for this will probably be found here: https://github.com/vincentarelbundock/countrycode/issues/67
