### ISSUE TITLE
Serbia and Montenegro is not in there separately

### ISSUE THREAD

**Issue by kendonB** [vincentarelbundock/countrycode#51]
Could consider adding this with, for example, the reserved iso3c "SCG"

**Comment by briatte** [comment]
As far I can tell, both Montenegro and Serbia were [already there](https://github.com/vincentarelbundock/countrycode/blob/d7aff6693f850b9a17166edaad76e33dd1939828/data/countrycode_data.csv) in October 2015.

**Comment by kendonB** [comment]
Correct. I'm saying "Serbia & Montenegro" (SCG) is not there as its own
single entry. Hope this clears this up! Thanks

**Comment by briatte** [comment]
Alright, that makes sense. Will fix in my next PR.
