### ISSUE TITLE
Accents don't seem to be handled right

### ISSUE THREAD

**Issue by kendonB** [vincentarelbundock/countrycode#57]
> countrycode("Curaçao", "country.name", "iso3c")
    [1] NA # Should work
    > countrycode("Curacao", "country.name", "iso3c")
    [1] "CUW" # works

**Comment by alistaire47** [comment]
A simple solution: preprocess strings with `stringi::stri_trans_general( ... , 'Latin-ASCII')`. 

For example,

```{r}
> library(stringi)
> stri_trans_general('Curaçao', 'Latin-ASCII')
[1] "Curacao"
> stri_trans_general('Israël', 'Latin-ASCII')
[1] "Israel"
> stri_trans_general('üìéøôçåßñ', 'Latin-ASCII')
[1] "uieoocassn"
```
There's [an old Nabble thread](http://r.789695.n4.nabble.com/remove-accents-in-strings-td2530089.html) that suggests using `iconv( ... , to = 'ASCII//TRANSLIT')`, but I found that inconsistent:
```{r}
> iconv('üìéøôçåßñ', to = 'ASCII//TRANSLIT')
[1] "\"u`i'eo^ocass~n"
```

**Comment by briatte** [comment]
@kendonB What's your session info? It works fine on my end:

```
> countrycode("Curaçao", "country.name", "iso3c")
[1] "CUW"
```

I'm French but running R in an English locale on Mac OS X:

```
R version 3.2.4 (2016-03-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] countrycode_0.18

loaded via a namespace (and not attached):
[1] tools_3.2.4
```

**Comment by kendonB** [comment]
This is working for me now. Not sure what changed.

**Comment by alistaire47** [comment]
`"Curaçao"` works fine for me, but `"Israél"` doesn't; I think there's still an underlying issue in handling accented characters.

**Comment by briatte** [comment]
"`Israél`" is not part of the regex match for Israel; see [line 119](https://github.com/vincentarelbundock/countrycode/blob/master/data/countrycode_data.csv#L119) of the country data.

**Comment by alistaire47** [comment]
I'm aware, but it still seems like a good idea to strip them out generally before trying to match the regex, because you're dealing with pretty much all the languages of the world here, and it gives you the best chance of getting it right regardless. You can leave the accents in the names returned, anyway; you just don't want them in the middle.

**Comment by briatte** [comment]
I understand your point, but I would argue instead for localized regexes. If you try to write regexes for fully unaccented country names that work in all languages, you quickly get unresolvable conflicts between the regexes. Also, I'm not sure whether the package should correct for typos (unless "Israél" is the correct spelling in a given language).

**Comment by kendonB** [comment]
My opinion is that the package should definitely account for common
misspellings, as datasets far too often get country names slightly
incorrect.

On Tue, Mar 29, 2016 at 9:22 PM, François Briatte <notifications@github.com>
wrote:

> I understand your point, but I would argue instead for localized regexes.
> If you try to write regexes for fully unaccented country names that work in
> all languages, you quickly get unresolvable conflicts between the regexes.
> Also, I'm not sure whether the package should correct for typos (unless
> "Israél" is the correct spelling in a given language).
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/vincentarelbundock/countrycode/issues/57#issuecomment-203240514>
>



-- 
Kendon Bell
Email: kmb56@berkeley.edu
Phone: (510) 612-3375

Ph.D. Candidate
Department of Agricultural & Resource Economics
University of California, Berkeley

**Comment by briatte** [comment]
Right now, the package deals with common misnamings, but not misspellings. Sometimes, both things are the same: in French, we write "Irak" instead of "Iraq".

To deal with misspellings, one might need to introduce match probabilities, using something like [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance). That's an interesting idea, but it's very far from what the package can do in its current state.
