### ISSUE TITLE
World Bank Income Class mapping

### ISSUE THREAD

**Issue by BDalheimer** [vincentarelbundock/countrycode#59]
First of all, many thanks for providing this great package! I have been using it a lot recently and found that it would be great if there was an option to map countries to their income group as classified by the World Bank (i.e. High Income, Upper-Middle Income, Lower-Middle Income and Low Income).

**Comment by vincentarelbundock** [comment]
Thanks a lot for the suggestion. I like it, but I sense feature creep: it's trivial (literally 2 lines of code) to merge this from the WDI() output, so I think I'll just let it go.
