### ISSUE TITLE
Country Code for "Kosovo"

### ISSUE THREAD

**Issue by andneuma** [vincentarelbundock/countrycode#61]
Hey,

according to https://countrycode.org/kosovo the country code for Kosovo is 'XKX' which does not seem to be coded within countrydata

Edit: iso3 code!

**Comment by NilsEnevoldsen** [comment]
No ISO country code that begins with an "X" is in the ISO standard. All such codes are explicitly reserved for individuals to assign for their own purposes ("User-assigned code elements"). I've seen XKX, XKS, and XKV for Kosovo, for example.

**Comment by vincentarelbundock** [comment]
Hey @NilsEnevoldsen thanks for the comments and info. I'm setting aside time to deal with some of these issues tonight. Would be useful if you could include an explicit recommendation for dealing with the issues you looked into in more detail.

I image that, here, we go with "Close", right?

**Comment by NilsEnevoldsen** [comment]
Yes, this is a WONTFIX. Ideally, we'd map XKX, XKS, XKV to Kosovo (since there's really no scope for confusion there), but Kosovo to NA. Since there's no way to do that short of a major refactoring, we should just close this.

**Comment by vincentarelbundock** [comment]
Thanks!
