### ISSUE TITLE
Allow custom mappings dictionary

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#67]

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countrycode/issues/63

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countrycode/issues/55

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countrycode/issues/50

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countrycode/issues/40

**Comment by vincentarelbundock** [comment]
I finally added a mechanism to allow user-provided custom translation dictionaries. I think this solves one of the issues you raised (linked above). See README

Do you like the new syntax?

Also, I added an "extra" folder in the data dictionary to host "clean" custom dictionaries for codes we may not want to add to the main package yet (for whatever reason).

@NilsEnevoldsen 
@nroming
@kendonB
@briatte
@LaDilettante
@espinielli

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countrycode/commit/8e78a6fe764654bcce40fafb34fd99a7fa77b601

**Comment by espinielli** [comment]
Looks fine for me 
It looks like in order to avoid disabling of sanity checks you need to pass maybe a vector specifying what in the custom dict can be destination-only...I do not know...

Anyway thanks a lot!

**Comment by LaDilettante** [comment]
Custom dictionary is a great solution! The syntax is also very straight forward, unless there's something in particular that you're worried about.
