### ISSUE TITLE
Faulty detection of country strings when sourcevar vector is passed using matrix-style subsetting

### ISSUE THREAD

**Issue by mberneaud** [vincentarelbundock/countrycode#70]
First of all, thank you very much for your work on the countrycode package. As a scholar in international relations who has to deal with country-level data frequently and with Correlates of War data all the time, your package is a blessing. To help you in future development, I wanted to share this strange behaviour I encountered yesterday (and which is not mentioned in the documentation).

Yesterday, I tried to convert ISO-3166-1 country names into a different format using `countrycode(sourcedf[, 2], "country.name", "cown")`, which didn't work correctly. Instead of creating different countrycodes for each row in the observations, the function pasted one country code into all rows (the second to last or third to last). Moreover, the warning message said that multiple expressions in the strings had been matched multiple times, including nearly all strings in the vector and some ISO3C codes which were not even part of the sourcevar vector (that last bit surprised me the most).

I then tried naming the sourcevar column and subsetting the dataframe with list-type subsetting using `$`, which worked as intended. Nevertheless, I was strangely surprised by the behavior the function showed when using matrix-style subsetting, which prompted me to submit an issue here.

**Comment by vincentarelbundock** [comment]
Happy the package is useful. 

Is sourcedf[, 2] just a standard vector, or is it a list housed in a column of the df?

Can you give me a reproducible example of the behavior. Without that, it'll be hard for me to diagnose. I

**Comment by mberneaud** [comment]
The data comes from reading in an excel sheet containing UNCTAD data on FDI inflows in China [Link](https://my.mixtape.moe/pstlvq.xls) with the readxl package's `read_excel()` function, which creates a dataframe with the classes "data.frame" and "tbl_df". It seems that these classes are inherited when subsetting using matrix-style subsetting, but not when list-style subsetting is used. 

```R
> class(infl[, 2])
[1] "tbl_df"     "data.frame"
> str(infl[, 2])
Classes ‘tbl_df’ and 'data.frame':	40 obs. of  1 variable:
 $ b: chr  NA "Austria" "Belgium" "Denmark" ...

> class(infl$a)
[1] "character"
> str(infl$b)
 chr [1:40] NA "Austria" "Belgium" "Denmark" "Finland" "France" "Germany" "Greece" ...
```
I suspect that this is the major problem which causes the bug, but it seems that it is caused by reading in the data with `read_excel()`. Regular data.frames which are created with `read.csv` or `read.table()` return vectors when subsetted with matrix-style subsetting. E.g: 

```R
> str(mtcars[, 2])
 num [1:32] 6 6 4 6 8 6 8 4 4 6 ...
> class(mtcars[, 2])
[1] "numeric"
```


**Below is the entire code which I used in case you want to reproduce it:**
```R
infl <- read_excel("raw_data/UNCTAD/ChinaFDI.xls",
                 sheet = 1,
                 skip = 4,
                 col_names = TRUE)

 
infl <- infl[5:nrow(infl), 4:ncol(infl)]

opposite <- is.na(infl[, 1]) & is.na(infl[, 2])
infl <- infl[!opposite, ]

infl$cown <- countrycode(infl[, 2], "country.name", "cown")
# Produces the wrong output

names(infl)[1:2] <- c("a", "b")

infl$cown <- countrycode(infl$b, "country.name", "cown")
# Produces the correct output

```

**Comment by vincentarelbundock** [comment]
So, is it fair to say this isn't a bug with ``countrycode`` per se? 

To be perfectly honest, I don't have much time to maintain this package, and I'd rather not try supporting every single data format outside base::R. 

If you can make a PR to improve compatibility, I might be able to consider it.

**Comment by mberneaud** [comment]
No, it's not a problem with the countrycode package per se. I'll see if I fint the time to implement the support for tbl_df classes and send you a pull request. 

Thanks for your quick replies, in any case.

**Comment by cjyetman** [comment]
This happens because dplyr/tibble rewrites `[` to *never* drop/simplify, i.e. it always returns a data.frame/tbl_df, even if the result is just one column. You could replace `infl[, 2]` with `infl[[2]]` to get just a vector, which countrycode will handle properly. I suppose one could argue that countrycode could/should be smart enough to coerce a single column data.frame to a vector for its sourcevar.

**Comment by vincentarelbundock** [comment]
Thanks for the diagnosis. If that's ever added to a PR, we just need to make sure to have an in-code annotation which records the reason for pre-processing. Also need to think about what format of output to spit out.

But just to reiterate, I fear that things can get pretty messy if countrycode is expected to 1-detect_class/2-coerce/3-countrycode/4-custom_output_based_on_input.

I'd rather concentrate on 3, but could potentially see arguments for common formats and mistakes.

**Comment by cjyetman** [comment]
I totally agree that trying to guess what the user wants when they gave you the wrong input is a fool's game... in my opinion the best resolution would be to check that `sourcevar` is a vector before anything and give a proper error if not.

**Comment by vincentarelbundock** [comment]
Right. The warning message could even include a specific mention of tibbles if that's a common use case.

**Comment by vincentarelbundock** [comment]
@cjyetman Is this issue fixed?

**Comment by cjyetman** [comment]
If you pass a one column tibble as sourcevar (for instance, by doing `my_tbl_df[, 2]`), you will get an error saying 'sourcevar must be a character or numeric vector'... which should be a sufficient error for a moderately knowledgable user to figure out how to fix the problem. (error added in commit #87)

**Comment by vincentarelbundock** [comment]
I wouldn't be averse to an even more explicit warning. How about:

'sourcevar must be a character or numeric vector. This error often arises when users pass a tibble (e.g., from dplyr) instead of a column vector from a data.frame (i.e., my_tbl[, 2] vs. my_df[, 2] vs. my_tbl[[2]])'
