### ISSUE TITLE
Implement detect_aggr

### ISSUE THREAD

**Issue by kendonB** [vincentarelbundock/countrycode#73]

**Comment by kendonB** [comment]
Get aggregate names from https://esa.un.org/unpd/wpp/DVD/Files/1_Indicators%20(Standard)/ASCII_FILES/WPP2015_DB02_Populations_Annual.zip

and WDI

**Comment by vincentarelbundock** [comment]
In general, I think we should limit the number of arguments to the main function; we don't want to complicate the API with thousands of switches. Would it be possible to just add an "aggregate" column to the CSV file with appropriate regexes?

**Or maybe do it as a different function**

**Comment by vincentarelbundock** [comment]
Since there are too many potential aggregates (even worse than the number of country codes), I don't think this is really a solvable problem. I recommend using the new custom dictionary option.
