### ISSUE TITLE
Regex issue: "Korea DPR" matches to "KOR" instead of "PRK"

### ISSUE THREAD

**Issue by tonyfujs** [vincentarelbundock/countrycode#74]
Hi,

The following returns the wrong country code:

```
countrycode("Korea DPR", origin = "country.name", destination = "wb")
[1] "KOR"
```

I'll try to look at it on my end, and will file a pull request if I figure out a robust solution.

Thanks,

**Comment by vincentarelbundock** [comment]
Is that with GitHub master? There have been several changes to reflexes since last CRAN version.

**Comment by tonyfujs** [comment]
I was using the CRAN version, but I get the same output using the Github master.

```
devtools::install_github('vincentarelbundock/countrycode')
library(countrycode)
countrycode("Korea DPR", origin = "country.name", destination = "wb")
[1] "KOR"
```

**Comment by vincentarelbundock** [comment]
The only thing that needs to be modified are the two corresponding lines (or just one of them) of the countrycode_data.csv file: 

```
Korea, Democratic People's Republic of	PRK	731	116	KN		PRK	KP	PRK	408	408	PRK	^(?=.*democrat).*\bkorea|^(?=.*people).*\bkorea|^(?=.*north).*\bkorea|dprk	Asia	Eastern Asia		ASIA
Korea, Republic of	ROK	732	117	KS	542	KOR	KR	KOR	410	410	KOR	^(?!.*democrat)(?!.*people)(?!.*north).*\bkorea
```

**Comment by sebastian-c** [comment]
In addition, it should match "D.P.R Korea"

**Comment by vincentarelbundock** [comment]
Added a test for korea. It fails currently, so we still need better regexes to differentiate the two.

df433c4492

**Comment by cjyetman** [comment]
also, in the current dev version of countrycode_data.csv...

ar5 = 'ASIA' for cowc = 'KOR' (Korea 1187-1905)
ar5 = '' for cowc = 'ROK' (South Korea 1949-present)

I assume that's a mistake?

**Comment by cjyetman** [comment]
I'm no regex wizard, but these update regexes will catch the examples in this issue...
```r
KORstrings <- c('South Korea', 'Republic of Korea', 'Korea, Republic of')
PRKstrings <- c('North Korea', 'DPRK', 'Korea DPR', 'Korea D.P.R.', 'DPR Korea', 
                 'D.P.R. Korea', 'D.P.R Korea', "Democratic People's Republic of Korea",
                 "Korea, Democratic People's Republic")

KORregex <- '^(?!.*d.*p.*r)(?!.*democrat)(?!.*people)(?!.*north).*\\bkorea(?!.*d.*p.*r)'
PRKregex <- '^(?=.*democrat|people|north|d.*p.*.r).*\\bkorea|dprk|korea.*(d.*p.*r)'

grepl(KORregex, KORstrings, perl = T, ignore.case = TRUE)
grepl(PRKregex, KORstrings, perl = T, ignore.case = TRUE)

grepl(KORregex, PRKstrings, perl = T, ignore.case = TRUE)
grepl(PRKregex, PRKstrings, perl = T, ignore.case = TRUE)
```

however, it seems like the strategy of the current, past, and this above regex for South Korea is to match on any string that contains "Korea", but excluding any of them that include something that might suggest North Korea (e.g. "DPR", "North", etc.)... considering there is an entry in countrycode_data.csv for cowc = 'KOR' (Korea 1187-1905), maybe the South Korea regex should be a little more explicit about it being either "South Korea", "Republic of Korea", "Korea, Republic of"?
