### ISSUE TITLE
Taiwan: has FAO code 214

### ISSUE THREAD

**Issue by MatthieuStigler** [vincentarelbundock/countrycode#75]
Taiwan has missing fao code in countrycode::countrycode_data:

    subset(countrycode::countrycode_data , iso3c=="TWN")

Code is actually 214, see for example: http://www.fao.org/faostat/en/#definitions

**Comment by vincentarelbundock** [comment]
Thanks. Fixed in https://github.com/vincentarelbundock/countrycode/commit/104cb73326fcc750392cf5fbfffd50e6da901c3b

Probably won't be releasing a CRAN version too soon, but you can install from github in the meantime:

```
library(devtools)
install_github('vincentarelbundock/countrycode')
```
