### ISSUE TITLE
some US territory country names have multiple matches in the regex strings

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#79]
given the current regex strings in [countrycode_data.csv](https://github.com/vincentarelbundock/countrycode/blob/master/data/countrycode_data.csv), the following strings have multiple matches:
```
'United States Minor Outlying Islands'
'United States Virgin Islands'
'Virgin Islands, U.S.'
```

**Comment by cjyetman** [comment]
I suspect this is a regression caused by [commit 7db3d6e2e77439c958f96d7790c26bf0f438539c](https://github.com/vincentarelbundock/countrycode/commit/7db3d6e2e77439c958f96d7790c26bf0f438539c)

**Comment by vincentarelbundock** [comment]
hack solution: put USA further down in the list. Eventually will need better regexes, as lots of warnings are now triggered by the tests (since warn=TRUE is now the new default).
