### ISSUE TITLE
sanity check on custom dictionary

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#82]
I propose doing a sanity check when a custom dictionary is passed. It should be able to...

- check that the custom dictionary is a data frame
- check if the `origin` and `destination` codes exist in the custom dictionary
- possibly check if the `origin` and `destination` code vectors have duplicated values
- stop with a message if a problem is found

anything else?

**Comment by vincentarelbundock** [comment]
Comment for future reference: Duplicates are only a problem for origin codes, not destination codes.

a5c44ec
