### ISSUE TITLE
enable case-insensitive matching of non-regex origin codes

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#84]
Currently, non-regex origin codes use case-sensitive matching. This results in...

`countrycode('usa', 'iso3c', 'country.name')` returning `NA`, while
`countrycode('USA', 'iso3c', 'country.name')` returns `"United States"`

countrycode could use `toupper()` on the sourcevar when origin is non-regex and a character vector to enable pseudo case-insensitivity, or the matching for non-regex character vectors could use `grep()` or a similar function that allows for case-insensitive matching.

**Comment by vincentarelbundock** [comment]
2ccba86
