### ISSUE TITLE
add possible origin and destination arguments to Arguments section of help

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#85]
Adding all possible origin and destination arguments to the `@param` section of the documentation will allow RStudio's autocomplete to display all valid argument values in the inline help, which could be a bit easier than pulling up the help file in the viewer panel.

**Comment by vincentarelbundock** [comment]
I don't use RStudio. How does it parse the ``@param`` description? What would be the proper way to include all possible values of the string in there?

**Comment by cjyetman** [comment]
As far as I can tell, it simply displays any text used to describ`#' @param origin ` the argument in the help file in the Arguments section... so whatever text comes after `#' @param origin ` will be displayed (line 9 in countrycode.R)

I would suggest something like:
`#' @param origin Coding scheme of the sourcevar: one of "country.name", "iso3c", etc.`

I can create a PR and test it, but not tonight. 

Here's an [example](http://www.rstudio.com/images/docs/using_console_completion_args.png) of what it looks like.

**Comment by vincentarelbundock** [comment]
thanks. that's fine; I'll have to edit the docs for my changes tonight anway. thanks again.

**Comment by vincentarelbundock** [comment]
I think this https://github.com/vincentarelbundock/countrycode/commit/6ad95c122f42d1af3f9994486f1e3e6238943abe fixes this issue. @cjyetman could you try it out to see if RStudio picks up on the information? 

Also, the notes now refer to the countrycode_data.Rd documentation. That way, it won't be such a pain to update next time.

**Comment by cjyetman** [comment]
Looks good to me...
<img width="650" alt="RStudio auto-complete inline help for origin" src="https://cloud.githubusercontent.com/assets/1708872/21536331/dfbd864a-cd81-11e6-9c90-e87041d13e7e.png">
<img width="653" alt="RStudio auto-complete inline help for destination" src="https://cloud.githubusercontent.com/assets/1708872/21536332/dfbf60be-cd81-11e6-8256-da20a735435c.png">

**Comment by vincentarelbundock** [comment]
looks fantastic. thanks for the tip.
