### ISSUE TITLE
add non-standard and/or case-insensitive evaluation of origin and destination arguments

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#86]
countrycode could be modified to accept non-standard (unquoted) and/or case-insensitive arguments to the origin and destination parameters, thereby allowing all of the following to work the same way...

```r
countrycode('Germany', 'country.name', 'iso3c')
countrycode('Germany', country.name, iso3c)
countrycode('Germany', 'country.name', 'ISO3c')
```

**Comment by vincentarelbundock** [comment]
How much code does this add? And is this much of a benefit? My sense is that non-standard evaluation is pretty unorthodox outside of Hadley-verse, and it seems reasonable to expect that users will use proper inputs (especially given that they're really simple strings). 

Thought I do agree with https://github.com/vincentarelbundock/countrycode/issues/82 that sanity checks could be improved.

**Comment by cjyetman** [comment]
This would be a safe way to do it (as far as I know).
```r
if (!exists(as.character(substitute(origin)))) {
      groupname <- as.character(substitute(origin))
    }
    origin <- tolower(origin)
```
It checks if an object with a name equal to the unquoted value exists first, if not it uses the unquoted value as a string, otherwise it uses the the value of the existing object. That allows, for instance, for a user to store the value they want in an object and pass that to countrycode, like...
```r
mytype <- 'iso3c'
countrycode('USA', mytype, 'iso3n')
```
It would introduce a possible confusion, if for instance someone did this...
```r
iso3c <- 'cow'
countrycode('USA', iso3c, iso3n)
```
in which case the origin would be processed as 'cow' since that is the value of the object `iso3c`, and the destination would be processed as 'iso3n' because no object with that name exists, so the name itself is assumed to be the value. That's a possible, but very convoluted situation that I think someone would have to go out of their way to create.

**Comment by cjyetman** [comment]
In terms of benefit... I have no desire to get in a debate about NSE. I remember the days when I thought NSE was complete blasphemy. After fully indulging in Hadley-verse (and realizing that at least a handful of very common base functions use it), I tend to appreciate it. So I see both sides.

I woud not say that this adds a lot of benefit, though I'm not sure how one would measure that. It's a rather safe change that some may appreciate, but I fully respect a strategy of keeping things simple.

**Comment by vincentarelbundock** [comment]
Right. I'm not dogmatic enough to reject NSE a priori, and I do appreciate the benefits for ggplot and such, but countrycode's functionality is so simple that I'd like to keep to KISS for core code, beefing up the sanity checks to give informative warnings. So I'm going to close this one, I think.
