### ISSUE TITLE
add a Eurostat origin/destination

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#93]
as discussed here: https://github.com/rOpenGov/eurostat/issues/54
"The European Commission and the Eurostat generally uses ISO 3166-1 alpha-2 codes with two exceptions: EL (not GR) is used to represent Greece, and UK (not GB) is used to represent the United Kingdom."

Eurostat is probably of sufficient prominence to justify offering its coding scheme as an origin/destination.

Finding the canonical definition is difficult, but here's a start...
- [geo.dic (en) file from bulk download](http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=dic%2Fen%2Fgeo.dic)
- [Eurostat Statistics Explained - Glossary:Country_codes](http://ec.europa.eu/eurostat/statistics-explained/index.php/Glossary:Country_codes)
- [GEONOM -Nomenclature of Countries and Territories for the External Trade Statistics of the Community and Statistics of Trade between Member States](http://ec.europa.eu/eurostat/ramon/other_documents/geonom/)
- [List Eurostat, EEA and FAO country codes side-by-side](http://www.eea.europa.eu/data-and-maps/daviz/eionet/data/eionet-data/list-eurostat-eea-and-fao-country-codes-side-by-side/@@view)
- [CSV - List Eurostat, EEA and FAO country codes side-by-side](http://www.eea.europa.eu/data-and-maps/daviz/eionet/data/eionet-data/list-eurostat-eea-and-fao-country-codes-side-by-side/download.csv)

**Comment by cjyetman** [comment]
Here's some code that downloads the Eurostat geo.dic, matches each line to countrycode's country.name, checks for problems, then rematches after making some necessary manual adjustments. I guess at this point we would still be adding these codes to countrycode_data.csv manually?
```r
# Eurostat
library(dplyr)
library(countrycode)
packageVersion("countrycode")

url <- 'http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=dic%2Fen%2Fgeo.dic'
eurostat <- read.delim(url, header = F, stringsAsFactors = F)

df <-
    eurostat %>%
    filter(nchar(V1) == 2) %>%  # only 2 character codes are countries
    filter(!is.na(V1)) %>%  # remove lines without data
    mutate(country.name = countrycode(V2, 'country.name', 'country.name')) %>%
    select(country.name, eurostat = V1, eurostat.name = V2)

df %>% filter(is.na(country.name))  # unmatched countries
df %>% filter(duplicated(country.name) | duplicated(country.name, fromLast = T)) %>% arrange(country.name)  #duplicate matches

df <-
    eurostat %>%
    filter(nchar(V1) == 2) %>%  # only 2 character codes are countries
    filter(!is.na(V1)) %>%  # remove lines without data
    filter(V1 != 'EU' & V1 != 'EA') %>%  # remove European Union and Euro Area
    filter(V2 != 'France (metropolitan)') %>%
    filter(V2 != 'Clipperton (FR)') %>%
    filter(V2 != 'Franc Zone') %>%
    filter(V2 != 'Investment Facility') %>%
    filter(V2 != 'Tibet (under the administration of China)') %>%
    mutate(name.fixed = V2) %>%
    mutate(name.fixed = if_else(name.fixed == 'Puerto Rico (US)', 'Puerto Rico', name.fixed)) %>%
    mutate(name.fixed = if_else(name.fixed == 'Guam (US)', 'Guam', name.fixed)) %>%
    mutate(name.fixed = if_else(name.fixed == 'Northern Mariana Islands (US)', 'Northern Mariana Islands', name.fixed)) %>%
    mutate(name.fixed = if_else(name.fixed == 'American Samoa (US)', 'American Samoa', name.fixed)) %>%
    mutate(name.fixed = if_else(name.fixed == 'United States Minor Outlying Islands (US)', 'US Minor Outlying Islands', name.fixed)) %>%
    mutate(name.fixed = if_else(name.fixed == 'US Virgin Islands (US)', 'US Virgin Islands', name.fixed)) %>%
    mutate(name.fixed = if_else(name.fixed == 'China (including Hong Kong)', 'China', name.fixed)) %>%
    mutate(name.fixed = if_else(name.fixed == 'Saint Martin (FR)', 'Saint Martin (French part)', name.fixed)) %>%
    mutate(country.name = countrycode(name.fixed, 'country.name', 'country.name')) %>%
    select(country.name, eurostat = V1, eurostat.name = V2)

df %>% filter(is.na(country.name))  # unmatched countries
df %>% filter(duplicated(country.name) | duplicated(country.name, fromLast = T)) %>% arrange(country.name)  #duplicate matches

```

**Comment by vincentarelbundock** [comment]
Can you add this to country year repo under "utilities"? Filename: download_eurostat.R. And have it save a CSV file to the raw folder.

When all the raw files are downloaded, we can have a different script merge everything into a cross sectional and a panel datasets.

**Comment by cjyetman** [comment]
will do
