### ISSUE TITLE
deal with duplicate matches differently than non-matches

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#94]
`countrycode` currently gives two types of warnings:
- "Some values were not matched: "
- "Some strings were matched more than once: "

In practice, the first is typically much more common, causes much more output in the warning, and is the result of what is probably expected behavior for most users (they realize some strings will not match a country and expect it to be NA so they can filter them out later).

The second one is less common, but a much bigger problem and is the result of potentially very unexpected, unpredictable behavior (from the user's perspective) (`countrycode` ~arbitrarily chooses one of its matches and returns it).

Maybe it makes sense that the first should be a `warning` while the second should be an `error`? Of course, that would cause an issue where users with strings that have multiple matches would always get an error, even though the parameters they are setting are appropriate, so they would need some way to ignore errors.

Alternatively, maybe duplicate matches should always return `NA` but still give a mandatory warning, while leaving warnings about non-matches opt-in (reverting the recent `warn=T` fix here #72 and here [b52eba6](https://github.com/vincentarelbundock/countrycode/commit/b52eba69d0e9acd8c35233e6894f3217415b4a61))

Which is worse for the user: getting the wrong code for a string that matched twice, or getting an NA for a string that matched but was ambiguous?

relevant, well reasoned thoughts (imo) about warnings vs. errors: [A Warning About warning()](http://blog.obeautifulcode.com/R/A-Warning-About-Warning/)

**Comment by vincentarelbundock** [comment]
I agree that the warnings should differentiate between those two problem cases.

Thanks for the link, that was a really interesting article.

In principle, it makes sense to me that we should move toward errors; I'm quite convinced by the general argument. However, I'm trying to think through the use experience here. 

Say Alice hits an error that tells her that some country name was matched by multiple regexes in our dictionary. Countrycode borks and refuses to give her an output. What are her options? Basically:

1. Fix the regex herself, or make a request on github (which will take lots of time)
2. Modify the offending string manually to make sure that it gets picked up by the correct regex, and only by the correct regex.

#1 doesn't seem very practical to me.

#2 either, because that would require reverse engineering our hard-coded regexes. I don't think we can ask users to do that.

**Comment by vincentarelbundock** [comment]
Also, in my experience, multiple matches usually affect things like "United States Minor Outlying Islands". Here, the order of the dictionary matters, and I think countrycode will usually (!) pick the correct one in practice. Of course, that's a bad design principle...

**Comment by cjyetman** [comment]
I lean towards returning `NA` for strings with multiple matches and printing a compulsory warning. I'd rather get an NA for a string that matched but was ambiguous than getting the wrong code for a string that matched more than one country.

My expectation, as a user, is that it will occasionally fail to determine the country, so getting an `NA` for something it could/should have matched is not such a big deal. On the other hand, getting the wrong code could be somewhat disastrous because I might not notice until much further down in my analysis... e.g. I might already be doing some comparisons and be really confused why a certain country has strange values until I work back through the process all the way to the original data to figure out what went wrong.

**Comment by vincentarelbundock** [comment]
Agreed. If you want to change this, I'll merge.

Why revert the warning change though? Seemed like a good idea to turn it on by default, and offer a switch for users who want to keep clean logs or something.

**Comment by vincentarelbundock** [comment]
And again, I really like the idea of different warnings for (a) no match, (b) multiple matches.

**Comment by cjyetman** [comment]
not necessary to revert `warn=TRUE`... it just occurred to me that some of the original intent for `warn=FALSE` as default was because the warnings were too 'talkative', but the argument for `warn=TRUE` as default was that some of the warnings are rather critical. The 'talkative' warnings are the 'not matched' type and are not critical, while the critical warnings are the 'multiple matches' type and are less frequent. So, maybe critical warnings should always show no matter what, while non-critical informational warnings could be default off (to resolve the dilemma of not showing lots warnings all the time, but making sure the user sees critical warnings).

**Comment by vincentarelbundock** [comment]
Except that with your proposed change, all warnings become "non critical".

Let's keep warn=TRUE as default for now. After a bit of dog-fooding we may change our minds.

**Comment by cjyetman** [comment]
true... maybe I see it as...
- non-match = `NA` (totally expected, non-critical)
- multiple matches = `NA`  (mostly non-critical, but I probably want to know about it because it's probably something I can fix)
- multiple matches = arbitrary choice of matching country codes (critical, I need to know)

but, if/when I get to this (returning `NA` for multiple matches), I will leave the default as is

**Comment by vincentarelbundock** [comment]
sounds great, thanks.

**Comment by cjyetman** [comment]
This is on hold until #117 and #79 are resolved. Otherwise tests fail because `countrycode` is relying on the order of rows in `countrycode_data` to choose the correct match of some country name matches.
