### ISSUE TITLE
add wb code that matches WB API codes

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode#98]
This was discussed here #62 a bit.

Apparently, if you download a CSV file from [databank.worldbank.org](http://databank.worldbank.org), the three letter country codes seem to match the destination='wb' countrycode results.

On the other hand, If you use the WB API or the WDI package to get the data, the 'wb' codes from countrycode do not match in a handful of cases. (Note: WDI only gets 2-letter codes by default, unless you set `extra = TRUE`)

Maybe we should add a 'wbapi' code that matches results from the API and the WDI package? Or maybe a 'wbapi2c' and a 'wbapi3c' code? here's the result of some experimentation (potential problem cases only)...
```
country                 wbapi2c  cc.iso2c  wbapi3c  wbcsv3c  cc.wb  cc.iso3c
Andorra                 AD       AD        AND      ADO      ADO    AND
British Virgin Islands  VG       VG        <NA>     VGB      VGB    VGB
Cabo Verde              CV       CV        <NA>     CPV      CPV    CPV
Channel Islands         JG       <NA>      CHI      CHI      <NA>   <NA>
Congo, Dem. Rep.        CD       CD        COD      ZAR      ZAR    COD
Faroe Islands           FO       FO        <NA>     FRO      FRO    FRO
Isle of Man             IM       IM        IMN      IMY      IMY    IMN
Kosovo                  XK       <NA>      <NA>     KSV      KSV    <NA>
Nauru                   NR       NR        <NA>     NRU      NRU    NRU
Romania                 RO       RO        ROU      ROM      ROM    ROU
Timor-Leste             TL       TL        TLS      TMP      TMP    TLS
West Bank and Gaza      PS       PS        PSE      WBG      WBG    PSE
```
thoughts on the best approach?

**Comment by vincentarelbundock** [comment]
Interesting!

Are we sure that the World Bank API *only* returns (incomplete-looking) ISO codes? I haven't looked at this in a while, but when I wrote ``WDI`` I specifically chose to save ISO codes (see https://github.com/vincentarelbundock/WDI/blob/master/R/WDI.R#L109). It's quite possible that the API can also return the same codes as in the CSV files.

**Comment by vincentarelbundock** [comment]
Also, the wb api version of iso3c seems to match the countrycode iso3c, except that some codes are missing (perhaps no data are available for those tiny islands?).

So one conclusion here, is that the WDI package properly labels the codes as iso3c, and that users should not try to treaty those as World Bank codes, since they're not.

Maybe that warrants adding a note to the WDI docs, but probably not integrating a whole bunch of new confusing codes.

Likewise, it seems like the WB API returns a few extra iso2c codes. We should look into whether it would be warranted to include those in our iso list.

**Comment by vincentarelbundock** [comment]
w.r.t. difference wbapi2c and iso2c, Kosovo was the subject of discussion in a different issue. It was decided to not include it because XK is not an official code, just a "temporary" one. Perhaps we can revisit. 

I don't know what's up with the Channel Islands.

**Comment by vincentarelbundock** [comment]
An alternative to entering a new code would be to include Channel Islands and Kosovo in the iso2c codes. Not exactly ISO-consistent, but it seems reasonable.

**Comment by cjyetman** [comment]
Personally, I value the consistency a lot, I think it's an expectation of the user, and frankly, I view it as black and white... it is either consistent, or it isn't, so I would strongly advocate for leaving iso consistent and looking for an alternate solution.

That being said, @vincentarelbundock you seem to value keeping the number origin/destination codes low. Is that a fair interpretation? Out of curiosity, is it because you fear the maintenance of too many codes (totally fair) or do you have other concerns as well?

I ask because this seems to be something that will/could come up frequently. 'This' being a request for a new origin/destination code that only has minor differences with an existing code. For instance, here (#98) we have a request for WB's API, here (#25) Polity IV scode, I just added (#93) Eurostat (which only has two differences with iso2c), I have code ready offline to pull in a new origin/destination for WVS (which also only has a handful of differences). Maybe we need a better solution for dealing with codes with only minor differences?

The custom dictionary would work, but in my experience in practice that feels like a rather 'heavy' solution... as in it seems like a lot of work for the user to do creating an entire custom dictionary, and once they have an entire custom dictionary created, it's questionable why they wouldn't just do a simple matching on the data frame or vectors they have created rather than feeding it back in to countrycode.

What do you think about something like a `custom_matches` option/argument to which one could supply a named vector of additional origin/destination matches that would supersede any of the default matching? Something like...
```r
countrycode(country_vector, 'country.name', 'iso3c', 
            custom_matches = c(`Channel Islands` = 'CHI', Kosovo = 'KSV'))
```
Eurostat would look like...
```r
countrycode(country_vector, 'country.name', 'iso2c', 
            custom_matches = c(Greece = 'EL', `United Kingdom` = 'UK'))
```
you could probably also then fix false matches like 'Southern Africa' by setting them to `NA` explicitly...
```r
countrycode(country_vector, 'country.name', 'iso3c', 
            custom_matches = c(`Southern Africa` = NA))
```

I know you also like to keep the number of potential options/arguments for the function minimized, but this could be quite useful and valuable, and possibly be a suitable solution for any future 'I need this code which is slightly different from..' and 'I need to explicitly exclude these group names/aggregates' (e.g. #73 and #71 ) requests?

**Comment by cjyetman** [comment]
btw... have to give a little credit to @christophergandrud because we were discussing something like this recently

**Comment by vincentarelbundock** [comment]
This is an interesting discussion.

I tend to agree with the idea that output should be faithful to some canonical reference code, which is exactly why it was decided not to include an iso3c for Kosovo.

I am sensitive to the problem of code proliferation in the dictionary. What I don't want, is for users who have not done the deep dive we have to be faced with 30 codes that are nearly indistinguishable, and to not know which one to choose.

I am also sensitive to the issue of maintainability. Managing too many small variations means I will probably have more work to do in the future. That's not such a high hurdle though; if the code is useful and we are reasonably sure that it will stay the same for a few years at least, then of course we should include it.

One solution to the proliferation of tiny variants would be to find a better naming scheme. For instance, we could have a "canonical" iso3c which conforms exactly to the current ISO spec, and then have "iso3c_wb", "iso3c_eurostat". That way, users would clearly see that those are derivatives, and users who don't know much will just default to baseline.

With respect to ``custom_matches``, I think that's a neat idea, but you're right to anticipate that my project maintainer reflex kicks in here. Is it worth adding a new switch to save 2 lines of code for corner-case users? The answer may be "yes", but I'm not 100% convinced yet:

```
library(countrycode)
custom_matches = c('Southern Africa'=NA, 'Kosovo'='KSV')
origin = c('United States', 'Southern Africa', 'Kosovo', 'Kosovo')
destination = countrycode(origin, 'country.name', 'iso3c')

# I'm sure there's a more concise way to do this below
m = match(origin, names(custom_matches))
destination = ifelse(is.na(m), destination, custom_matches[m])
```

**Comment by cjyetman** [comment]
hehe... you're totally right about the alternate, out-of-package solution for `custom_matches = `. That's exactly how I've begun to feel about `dictionary = `, it seems nice, but why not just do it on your own if you have created the dictionary already anyway?

looking at alternate methods...
```r
# given
library(countrycode)
origin <- c('South Africa', 'Central and South Africa countries', 'Kosovo')
countrycode(origin, 'country.name', 'iso3c')
# [1] "ZAF" "ZAF" NA

# DIY
destination <- countrycode(origin, 'country.name', 'iso3c')
custom_matches <- c('Central and South Africa countries' = NA, 'Kosovo' = 'KSV')
m <- match(origin, names(custom_matches))
ifelse(is.na(m), destination, custom_matches[m])
# [1] "ZAF" NA    "KSV"

# custom_matches
custom_matches <- c('Central and South Africa countries' = NA, 'Kosovo' = 'KSV')
countrycode(origin, 'country.name', 'iso3c', custom_matches = custom_matches)
# [1] "ZAF" NA    "KSV"

# custom dictionary (can't easily fix the false match problem)
cust_dict <- countrycode_data
cust_dict$iso3c[cust_dict$country.name.en == 'Kosovo'] <- 'KSV'
countrycode(origin, 'country.name.en.regex', 'iso3c', dictionary = cust_dict, origin_regex = T)
# [1] "ZAF" "ZAF" "KSV"  (still fails on the South Africa mismatch)

# custom dictionary (convoluted way of avoiding mismatch breaks 
# the good matches, but might work in some use cases)
cust_dict <- countrycode_data[, c('iso3c', 'country.name.en', 'country.name.en.regex')]
cust_dict$iso3c[cust_dict$country.name.en == 'Kosovo'] <- 'KSV'
cust_dict <- cust_dict[-which(cust_dict$iso3c=='ZAF'), ]
countrycode(origin, 'country.name.en.regex', 'iso3c', dictionary = cust_dict, origin_regex = T, warn = T)
# [1] NA    NA    "KSV"

# custom dictionary (provide alternate regex that works, and 
# wonder why the package hasn't done this already)
cust_dict <- countrycode_data[, c('iso3c', 'country.name.en', 'country.name.en.regex')]
cust_dict$iso3c[cust_dict$country.name.en == 'Kosovo'] <- 'KSV'
cust_dict$country.name.en.regex[which(cust_dict$iso3c=='ZAF')] <- '^south.africa$|s\\\\..?africa'
countrycode(origin, 'country.name.en.regex', 'iso3c', dictionary = cust_dict, origin_regex = T, warn = T)
# [1] "ZAF" NA    "KSV"
```
you can probably imagine which I prefer. I feel like the `custom_matches = ` option kills two birds with one stone (false misses and false matches), and is very concise and easy to use.

However, I would vote for the "iso3c_wb" style variants as the preferred solution for specific codes that we know about.

**Comment by vincentarelbundock** [comment]
``dictionary`` is pretty useful, I think; have used the US state codes myself just last week.

In any case, the package is pretty minimalistic as is, so I guess it wouldn't be too bad to add another argument. And it does look kind of useful (thinking back, I can see times where it would probably have helped me).

[Also, part of me feels like I should be especially receptive to suggestions by the few people who have actually stepped up to help make the thing better.]

So if you're willing to implement new naming scheme and custom_matches, I say go ahead.

Also, I think the CRAN version doesn't have the dictionary argument yet. So there is still time to change the name to harmonize it. Should we do ``custom_dictionary`` and ``custom_matches``? And how do we explain the difference in the docs?

**Comment by vincentarelbundock** [comment]
I guess the key difference is that ``custom_matches`` is a sort of override on existing codes and the input is a named vector, while dictionary provides new codes and the input is a df.

**Comment by vincentarelbundock** [comment]
Another alternative would be to:

1. Accept named vectors in the dictionary argument
2. Add a switch to specify is custom dictionary conversion is applied "pre" or "post" conversion.

Not sure if that's clearer or more complicated.

**Comment by cjyetman** [comment]
in terms of a "new naming scheme" for similar code schemes... what's the definitive difference between a code scheme which should be considered a variant of one of the existing coding schemes, and a coding scheme that's sufficiently different to warrant having it's own unique name?

**Comment by cjyetman** [comment]
In terms of the argument names... personally, I prefer shorter argument names versus longer, even if that means using abbreviations... mostly because I'm annoyed by lines/commands that span more than 80 columns/characters or so. So, I might lean towards `cust_dict` and `cust_match` or something like that, though I understand why people prefer precise, meaningful, unambiguous argument names.

**Comment by vincentarelbundock** [comment]
If we're looking for "definitive difference", I think we'll be stuck here awhile :)

I know I just proposed the variants naming scheme idea, but bear me with a minute, since I'm processing this stuff as I write.

One counter argument to listing names with "original code stems", is that users are more likely to care/look for the name of the organization that published their data.

So I wonder if we want ``wb`` and ``wb_api`` or ``iso3c_wb`` and ``iso3c_wb_api``.

Let's split the difference and do ``custom_dict`` and ``custom_match``

**Comment by vincentarelbundock** [comment]
And say we want to add ``polity``'s scode? Are we going to use ``cowc_polity``, ``cowc_scode``, or just ``polity``?

I'm open to arguments (and undecided right now).

**Comment by cjyetman** [comment]
hmmmmm... combining the functionality into one argument is interesting. I would state the difference as append vs. overwrite, instead of pre vs. post. I think combining them is cool, but maybe would cause a lot of preprocessing inside the function. Not that I think it's not feasible.

**Comment by vincentarelbundock** [comment]
not add. Polity is already there. but do we rename?

**Comment by cjyetman** [comment]
My absolute preference is to add reasonably common coding schemes with their own unique "stem". So that would mean having `iso3c`, `wb`, `wb_api`, `polity_scode`, `polity_ccode`, `eurostat`, `wvs`, `eurobar`, `eucom`, etc. And then each would have a place and description in the help files, so they're easy to find. My thought is that the user doesn't care if the Eurostat code is similar to iso2c, s/he just expects it to work, and it's probably easier for them to figure out if they go to the help file, find `eurostat` and they're done... as opposed to finding `iso2c_eurostat` amongst a bunch of other iso2c variants.

I thought we were trying to minimize on the possible coding scheme names though, no? I also understand wanting to minimize the infrastructure to maintain, and trying to not let the CSV file grow to enormous size with heavy duplication.

**Comment by vincentarelbundock** [comment]
SOLD!

**Comment by cjyetman** [comment]
wb_api2c and wb_api3c added in #113
